{
	"version": 1579067370,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/expbar-sheet0.png",
		"images/exptext.png",
		"images/hpbar-sheet0.png",
		"images/invbutton-sheet0.png",
		"images/level.png",
		"images/mpbar-sheet0.png",
		"images/slotweapon-sheet0.png",
		"images/slotweapon-sheet1.png",
		"images/slotmagic-sheet0.png",
		"images/slotarmor-sheet0.png",
		"images/slotarmor-sheet1.png",
		"images/slot-sheet0.png",
		"images/slot-sheet1.png",
		"images/slot-sheet2.png",
		"images/ui.png",
		"images/label-sheet0.png",
		"images/slotspells-sheet0.png",
		"images/slotspells-sheet1.png",
		"images/slotspells-sheet2.png",
		"images/playermove-sheet0.png",
		"images/enemy-sheet0.png",
		"images/back.png",
		"images/weaponinhand-sheet0.png",
		"images/weaponinhand-sheet1.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/enemyhpbar-sheet0.png",
		"images/particles.png",
		"images/player-sheet0.png",
		"images/rock-sheet0.png",
		"images/weaponinhandenemy-sheet0.png",
		"images/blood-sheet0.png",
		"images/wraptonextlevel-sheet0.png",
		"images/spellsonground-sheet0.png",
		"images/spellsonground-sheet1.png",
		"images/charge-sheet0.png",
		"images/charge-sheet1.png",
		"images/charge-sheet2.png",
		"images/fireball-sheet0.png",
		"images/fireball-sheet1.png",
		"images/explosion-sheet0.png",
		"images/radar-sheet0.png",
		"images/radardots-sheet0.png",
		"images/dot-sheet0.png",
		"images/titleback-sheet0.png",
		"images/start-sheet0.png",
		"images/load-sheet0.png",
		"images/save-sheet0.png",
		"images/flash.png",
		"images/arrow-sheet0.png",
		"images/particles2.png",
		"images/bowinhand-sheet0.png",
		"images/radardots2-sheet0.png",
		"images/radardots3-sheet0.png",
		"images/chest-sheet0.png",
		"images/chest-sheet1.png",
		"images/coin-sheet0.png",
		"images/barell-sheet0.png",
		"images/particles4.png",
		"images/barell2-sheet0.png",
		"media/blow6.m4a",
		"media/blow6.ogg",
		"media/bow.m4a",
		"media/bow.ogg",
		"media/drinking water.m4a",
		"media/drinking water.ogg",
		"media/drop armor.m4a",
		"media/drop armor.ogg",
		"media/drop pistol.m4a",
		"media/drop pistol.ogg",
		"media/equip1wep.m4a",
		"media/equip1wep.ogg",
		"media/equip2cloth.m4a",
		"media/equip2cloth.ogg",
		"media/grab.m4a",
		"media/grab.ogg",
		"media/knife_hit3.m4a",
		"media/knife_hit3.ogg",
		"media/step1.m4a",
		"media/step1.ogg",
		"media/a metal weapon is dropped.m4a",
		"media/a metal weapon is dropped.ogg",
		"media/swingweapon.m4a",
		"media/swingweapon.ogg",
		"media/levelup.m4a",
		"media/levelup.ogg",
		"media/monsterdie1.m4a",
		"media/monsterdie1.ogg",
		"media/pig1.m4a",
		"media/pig1.ogg",
		"media/pig2.m4a",
		"media/pig2.ogg",
		"media/pig3.m4a",
		"media/pig3.ogg",
		"media/pigdead.m4a",
		"media/pigdead.ogg",
		"media/firebalshoot.m4a",
		"media/firebalshoot.ogg",
		"media/firewall.m4a",
		"media/firewall.ogg",
		"media/magicexplosion.m4a",
		"media/magicexplosion.ogg",
		"media/magicpickup.m4a",
		"media/magicpickup.ogg",
		"media/metalhit.m4a",
		"media/metalhit.ogg",
		"media/wood_bow_catapult_creak_1.m4a",
		"media/wood_bow_catapult_creak_1.ogg",
		"media/chest.ogg",
		"media/coin1.m4a",
		"media/coin1.ogg",
		"media/coin2.m4a",
		"media/coin2.ogg",
		"media/bullet wood hit 2.m4a",
		"media/bullet wood hit 2.ogg",
		"media/barrel break.m4a",
		"media/barrel break.ogg",
		"media/wood explosion.m4a",
		"media/wood explosion.ogg",
		"media/village.m4a",
		"media/village.ogg",
		"media/level_001.m4a",
		"media/level_001.ogg",
		"media/title_001.m4a",
		"media/title_001.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}