'use strict';window.DOMHandler=class{constructor(a,b){this._iRuntime=a;this._componentId=b;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(a,b,e,k){this._iRuntime.PostToRuntimeComponent(this._componentId,a,b,e,k)}PostToRuntimeAsync(a,b,e,k){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,a,b,e,k)}_PostToRuntimeMaybeSync(a,b,e){this._iRuntime.UsesWorker()?this.PostToRuntime(a,b,e):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:a,dispatchOpts:e||null,data:b,responseId:null})}AddRuntimeMessageHandler(a,b){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,a,b)}AddRuntimeMessageHandlers(a){for(const [b,e]of a)this.AddRuntimeMessageHandler(b,e)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(a,b){this._callback=a;this._interval=b;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(a){this._canRunImmediate=!!a}Call(){if(-1===this._timerId){var a=Date.now(),b=a-this._lastCallTime,e=this._interval;b>=e&&this._canRunImmediate?(this._lastCallTime=a,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(e-b,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(a,b){super(a,b);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",e=>this._OnCreate(e)],["destroy",e=>this._OnDestroy(e)],["set-visible",e=>this._OnSetVisible(e)],["update-position",e=>this._OnUpdatePosition(e)],["update-state",e=>this._OnUpdateState(e)],["focus",e=>this._OnSetFocus(e)],["set-css-style",e=>this._OnSetCssStyle(e)],["set-attribute",e=>this._OnSetAttribute(e)],["remove-attribute",
e=>this._OnRemoveAttribute(e)]]);this.AddDOMElementMessageHandler("get-element",e=>e)}SetAutoAttach(a){this._autoAttach=!!a}AddDOMElementMessageHandler(a,b){this.AddRuntimeMessageHandler(a,e=>{const k=this._elementMap.get(e.elementId);return b(k,e)})}_OnCreate(a){const b=a.elementId,e=this.CreateElement(b,a);this._elementMap.set(b,e);a.isVisible||(e.style.display="none");e.addEventListener("focus",k=>this._OnFocus(b));e.addEventListener("blur",k=>this._OnBlur(b));this._autoAttach&&document.body.appendChild(e)}CreateElement(a,
b){throw Error("required override");}DestroyElement(a){}_OnDestroy(a){a=a.elementId;const b=this._elementMap.get(a);this.DestroyElement(b);this._autoAttach&&b.parentElement.removeChild(b);this._elementMap.delete(a)}PostToRuntimeElement(a,b,e){e||(e={});e.elementId=b;this.PostToRuntime(a,e)}_PostToRuntimeElementMaybeSync(a,b,e){e||(e={});e.elementId=b;this._PostToRuntimeMaybeSync(a,e)}_OnSetVisible(a){this._autoAttach&&(this._elementMap.get(a.elementId).style.display=a.isVisible?"":"none")}_OnUpdatePosition(a){if(this._autoAttach){var b=
this._elementMap.get(a.elementId);b.style.left=a.left+"px";b.style.top=a.top+"px";b.style.width=a.width+"px";b.style.height=a.height+"px";a=a.fontSize;null!==a&&(b.style.fontSize=a+"em")}}_OnUpdateState(a){const b=this._elementMap.get(a.elementId);this.UpdateState(b,a)}UpdateState(a,b){throw Error("required override");}_OnFocus(a){this.PostToRuntimeElement("elem-focused",a)}_OnBlur(a){this.PostToRuntimeElement("elem-blurred",a)}_OnSetFocus(a){const b=this._elementMap.get(a.elementId);a.focus?b.focus():
b.blur()}_OnSetCssStyle(a){this._elementMap.get(a.elementId).style[a.prop]=a.val}_OnSetAttribute(a){this._elementMap.get(a.elementId).setAttribute(a.name,a.val)}_OnRemoveAttribute(a){this._elementMap.get(a.elementId).removeAttribute(a.name)}GetElementById(a){return this._elementMap.get(a)}};"use strict";
{var IsWebViewExportType=function(p){return l.has(p)},BlobToArrayBuffer=function(p){return new Promise((d,g)=>{const h=new FileReader;h.onload=n=>d(n.target.result);h.onerror=n=>g(n);h.readAsArrayBuffer(p)})},BlobToString=async function(p){p=await BlobToArrayBuffer(p);return(new TextDecoder("utf-8")).decode(p)},AddScript=function(p){if(p.isStringSrc){const d=document.createElement("script");d.async=!1;d.textContent=p.str;document.head.appendChild(d)}else return new Promise((d,g)=>{const h=document.createElement("script");
h.onload=d;h.onerror=g;h.async=!1;h.src=p;document.head.appendChild(h)})};const a=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let b=new Audio;const e={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),
"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;const k=[];let t=0;window.RealFile=window.File;const q=[],u=new Map,c=new Map;let f=0;const m=[];self.runOnStartup=function(p){if("function"!==typeof p)throw Error("runOnStartup called without a function");m.push(p)};const l=new Set(["cordova","playable-ad","instant-games"]);window.RuntimeInterface=class p{constructor(d){this._useWorker=d.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=d.scriptFolder;this._workerScriptBlobURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=d.exportType;IsWebViewExportType(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._transferablesBroken=!1;this._localFileStrings=
this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",g=>this._OnCordovaFetchLocalFile(g));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",g=>this._OnCreateJobWorker(g));
"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(d)):this._Init(d)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsiOSCordova(){return a&&
"cordova"===this._exportType}IsiOSWebView(){return a&&IsWebViewExportType(this._exportType)||navigator.standalone}async _Init(d){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let h=0,n=d.engineScripts.length;h<n;++h){var g=d.engineScripts[h].toLowerCase();this._localFileStrings.hasOwnProperty(g)?d.engineScripts[h]={isStringSrc:!0,str:this._localFileStrings[g]}:this._localFileBlobs.hasOwnProperty(g)&&
(d.engineScripts[h]=URL.createObjectURL(this._localFileBlobs[g]))}}d.baseUrl?this._baseUrl=d.baseUrl:(g=location.origin,this._baseUrl=("null"===g?"file:///":g)+location.pathname,g=this._baseUrl.lastIndexOf("/"),-1!==g&&(this._baseUrl=this._baseUrl.substr(0,g+1)));if(d.workerScripts)for(const [h,n]of Object.entries(d.workerScripts))this._workerScriptBlobURLs[h]=URL.createObjectURL(n);g=new MessageChannel;this._messageChannelPort=g.port1;this._messageChannelPort.onmessage=h=>this._OnMessageFromRuntime(h.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(h=>this._OnMessageFromDebugger(h));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this._TestTransferablesWork();this._useWorker?await this._InitWorker(d,g.port2):await this._InitDOM(d,g.port2)}_GetWorkerURL(d){return this._workerScriptBlobURLs.hasOwnProperty(d)?
this._workerScriptBlobURLs[d]:d.endsWith("/workermain.js")&&this._workerScriptBlobURLs.hasOwnProperty("workermain.js")?this._workerScriptBlobURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(d.toLowerCase())?URL.createObjectURL(this._localFileBlobs[d.toLowerCase()]):d}async CreateWorker(d,g,h){if(d.startsWith("blob:"))return new Worker(d,h);if(this.IsiOSCordova()&&"file:"===location.protocol)return d=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+
d),d=new Blob([d],{type:"application/javascript"}),new Worker(URL.createObjectURL(d),h);d=new URL(d,g);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),h)}return new Worker(d,h)}MaybeForceBodySize(){if(this.IsiOSWebView()){const d=document.documentElement.style,g=document.body.style,h=window.innerWidth<window.innerHeight,n=h?window.screen.width:window.screen.height;g.height=d.height=(h?window.screen.height:
window.screen.width)+"px";g.width=d.width=n+"px"}}_GetCommonRuntimeOptions(d){return{baseUrl:this._baseUrl,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:p.IsDocumentFullscreen(),projectData:d.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:d.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),
supportedAudioFormats:e,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(d,g){var h=this._GetWorkerURL(d.workerMainUrl);this._worker=await this.CreateWorker(h,this._baseUrl,{name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display=
"none";h=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(d),{type:"init-runtime",isInWorker:!0,messagePort:g,canvas:h,workerDependencyScripts:d.workerDependencyScripts||[],engineScripts:d.engineScripts,projectScripts:window.cr_allProjectScripts,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[g,h,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=q.map(n=>
new n(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(n,r)=>this._runtimeDomHandler._InvokeFunctionFromJS(n,r);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(d,g){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=q.map(n=>new n(this));this._FindRuntimeDOMHandler();const h=d.engineScripts.map(n=>
"string"===typeof n?(new URL(n,this._baseUrl)).toString():n);Array.isArray(d.workerDependencyScripts)&&h.unshift(...d.workerDependencyScripts);await Promise.all(h.map(n=>AddScript(n)));if(d.projectScripts&&0<d.projectScripts.length){const n=self.C3_ProjectScriptsStatus;try{if(await Promise.all(d.projectScripts.map(r=>AddScript(r[1]))),Object.values(n).some(r=>!r)){self.setTimeout(()=>this._ReportProjectScriptError(n),100);return}}catch(r){console.error("[Preview] Error loading project scripts: ",
r);self.setTimeout(()=>this._ReportProjectScriptError(n),100);return}}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this._GetCommonRuntimeOptions(d),{isInWorker:!1,messagePort:g,canvas:this._canvas,runOnStartupFunctions:m}),this._localRuntime=
self.C3_CreateRuntime(d),await self.C3_InitRuntime(this._localRuntime,d))}_ReportProjectScriptError(d){d=`Failed to load project script '${Object.entries(d).filter(g=>!g[1]).map(g=>g[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+d);alert(d)}async _OnCreateJobWorker(d){d=await this._jobScheduler._CreateJobWorker();return{outputPort:d,transferables:[d]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(d,
g,h,n,r){this._messageChannelPort.postMessage({type:"event",component:d,handler:g,dispatchOpts:n||null,data:h,responseId:null},this._transferablesBroken?void 0:r)}PostToRuntimeComponentAsync(d,g,h,n,r){const w=f++,v=new Promise((x,y)=>{c.set(w,{resolve:x,reject:y})});this._messageChannelPort.postMessage({type:"event",component:d,handler:g,dispatchOpts:n||null,data:h,responseId:w},this._transferablesBroken?void 0:r);return v}["_OnMessageFromRuntime"](d){const g=d.type;if("event"===g)return this._OnEventFromRuntime(d);
if("result"===g)this._OnResultFromRuntime(d);else if("runtime-ready"===g)this._OnRuntimeReady();else if("alert"===g)alert(d.message);else throw Error(`unknown message '${g}'`);}_OnEventFromRuntime(d){const g=d.component,h=d.handler,n=d.data,r=d.responseId;if(d=u.get(g))if(d=d.get(h)){var w=null;try{w=d(n)}catch(v){console.error(`Exception in '${g}' handler '${h}':`,v);null!==r&&this._PostResultToRuntime(r,!1,""+v);return}if(null===r)return w;w&&w.then?w.then(v=>this._PostResultToRuntime(r,!0,v)).catch(v=>
{console.error(`Rejection from '${g}' handler '${h}':`,v);this._PostResultToRuntime(r,!1,""+v)}):this._PostResultToRuntime(r,!0,w)}else console.warn(`[DOM] No handler '${h}' for component '${g}'`);else console.warn(`[DOM] No event handlers for component '${g}'`)}_PostResultToRuntime(d,g,h){let n;h&&h.transferables&&(n=h.transferables);this._messageChannelPort.postMessage({type:"result",responseId:d,isOk:g,result:h},n)}_OnResultFromRuntime(d){const g=d.responseId,h=d.isOk;d=d.result;const n=c.get(g);
h?n.resolve(d):n.reject(d);c.delete(g)}AddRuntimeComponentMessageHandler(d,g,h){let n=u.get(d);n||(n=new Map,u.set(d,n));if(n.has(g))throw Error(`[DOM] Component '${d}' already has handler '${g}'`);n.set(g,h)}static AddDOMHandlerClass(d){if(q.includes(d))throw Error("DOM handler already added");q.push(d)}_FindRuntimeDOMHandler(){for(const d of this._domHandlers)if("runtime"===d.GetComponentID()){this._runtimeDomHandler=d;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(d){this.PostToRuntimeComponent("debugger",
"message",d)}_OnRuntimeReady(){for(const d of this._domHandlers)d.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(d){this._rafCallbacks.push(d);this._RequestAnimationFrame()}_RemoveRAFCallback(d){d=this._rafCallbacks.indexOf(d);if(-1===d)throw Error("invalid callback");
this._rafCallbacks.splice(d,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const d of this._rafCallbacks)d();this._RequestAnimationFrame()}TryPlayMedia(d){this._runtimeDomHandler.TryPlayMedia(d)}RemovePendingPlay(d){this._runtimeDomHandler.RemovePendingPlay(d)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(d){this._runtimeDomHandler.SetSilent(d)}IsAudioFormatSupported(d){return!!e[d]}async _WasmDecodeWebMOpus(d){d=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}IsAbsoluteURL(d){return/^(?:[a-z]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}IsRelativeURL(d){return!this.IsAbsoluteURL(d)}async _OnCordovaFetchLocalFile(d){const g=d.filename;switch(d.as){case "text":return await this.CordovaFetchLocalFileAsText(g);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(g);default:throw Error("unsupported type");}}_GetPermissionAPI(){const d=
window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof d)throw Error("Permission API is not loaded");return d}_MapPermissionID(d,g){d=d[g];if("string"!==typeof d)throw Error("Invalid permission name");return d}_HasPermission(d){const g=this._GetPermissionAPI();return new Promise((h,n)=>g.checkPermission(this._MapPermissionID(g,d),r=>h(!!r.hasPermission),n))}_RequestPermission(d){const g=this._GetPermissionAPI();return new Promise((h,n)=>g.requestPermission(this._MapPermissionID(g,
d),r=>h(!!r.hasPermission),n))}async RequestPermissions(d){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const g of d)if(!await this._HasPermission(g)&&!1===await this._RequestPermission(g))return!1;return!0}async RequirePermissions(...d){if(!1===await this.RequestPermissions(d))throw Error("Permission not granted");}CordovaFetchLocalFile(d){const g=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((h,n)=>{window.resolveLocalFileSystemURL(g,
r=>{r.file(h,n)},n)})}async CordovaFetchLocalFileAsText(d){d=await this.CordovaFetchLocalFile(d);return await BlobToString(d)}_CordovaMaybeStartNextArrayBufferRead(){if(k.length&&!(8<=t)){t++;var d=k.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(d.filename,d.successCallback,d.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(d){return new Promise((g,h)=>{k.push({filename:d,successCallback:n=>{t--;this._CordovaMaybeStartNextArrayBufferRead();g(n)},errorCallback:n=>{t--;this._CordovaMaybeStartNextArrayBufferRead();
h(n)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(d,g,h){try{const n=await this.CordovaFetchLocalFile(d),r=await BlobToArrayBuffer(n);g(r)}catch(n){h(n)}}async _ConvertDataUrisToBlobs(){const d=[];for(const [g,h]of Object.entries(this._localFileBlobs))d.push(this._ConvertDataUriToBlobs(g,h));await Promise.all(d)}async _ConvertDataUriToBlobs(d,g){if("object"===typeof g)this._localFileBlobs[d]=new Blob([g.str],{type:g.type}),this._localFileStrings[d]=
g.str;else{let h=await this._FetchDataUri(g);h||(h=this._DataURIToBinaryBlobSync(g));this._localFileBlobs[d]=h}}async _FetchDataUri(d){try{return await (await fetch(d)).blob()}catch(g){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",g),null}}_DataURIToBinaryBlobSync(d){d=this._ParseDataURI(d);return this._BinaryStringToBlob(d.data,d.mime_type)}_ParseDataURI(d){var g=
d.indexOf(",");if(0>g)throw new URIError("expected comma in data: uri");var h=d.substring(5,g);d=d.substring(g+1);g=h.split(";");h=g[0]||"";const n=g[2];d="base64"===g[1]||"base64"===n?atob(d):decodeURIComponent(d);return{mime_type:h,data:d}}_BinaryStringToBlob(d,g){var h=d.length;let n=h>>2,r=new Uint8Array(h),w=new Uint32Array(r.buffer,0,n),v,x;for(x=v=0;v<n;++v)w[v]=d.charCodeAt(x++)|d.charCodeAt(x++)<<8|d.charCodeAt(x++)<<16|d.charCodeAt(x++)<<24;for(h&=3;h--;)r[x]=d.charCodeAt(x),++x;return new Blob([r],
{type:g})}_TestTransferablesWork(){let d=null;const g=new Promise(r=>d=r),h=new ArrayBuffer(1),n=new MessageChannel;n.port2.onmessage=r=>{r.data&&r.data.arrayBuffer||(this._transferablesBroken=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));d()};n.port1.postMessage({arrayBuffer:h},[h]);return g}}}"use strict";
{var KeyboardIsVisible=function(){const c=document.activeElement;if(!c)return!1;const f=c.tagName.toLowerCase(),m=new Set("email number password search tel text url".split(" "));return"textarea"===f?!0:"input"===f?m.has(c.type.toLowerCase()||"text"):IsInContentEditable(c)},ParentHasFocus=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}},BlockWheelZoom=function(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()},PreventDefaultOnCanvasOrDoc=function(c){const f=c.target.tagName.toLowerCase();
q.has(f)&&c.preventDefault()},IsInContentEditable=function(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1},BlobToSvgImage=async function(c,f,m){if(!/firefox/i.test(navigator.userAgent))return await BlobToImage(c);var l=await BlobToString$jscomp$1(c);l=(new DOMParser).parseFromString(l,"image/svg+xml");const p=l.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const d=p.getAttribute("width"),g=p.getAttribute("height");if(!d.includes("%")&&
!g.includes("%"))return await BlobToImage(c)}p.setAttribute("width",f+"px");p.setAttribute("height",m+"px");l=(new XMLSerializer).serializeToString(l);c=new Blob([l],{type:"image/svg+xml"});return await BlobToImage(c)},BlobToString$jscomp$1=function(c){return new Promise((f,m)=>{let l=new FileReader;l.onload=p=>f(p.target.result);l.onerror=p=>m(p);l.readAsText(c)})},BlobToImage=async function(c){c=URL.createObjectURL(c);try{return await FetchImage(c)}finally{URL.revokeObjectURL(c)}},FetchImage=function(c){return new Promise((f,
m)=>{const l=new Image;l.onload=()=>f(l);l.onerror=p=>m(p);l.src=c})},AddStyleSheet=function(c){return new Promise((f,m)=>{const l=document.createElement("link");l.onload=()=>f(l);l.onerror=p=>m(p);l.rel="stylesheet";l.href=c;document.head.appendChild(l)})},IsCompatibilityMouseEvent=function(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents};const a=self.RuntimeInterface,b=
new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),e={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},k={dispatchUserScriptEvent:!0},t={dispatchRuntimeEvent:!0},q=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(c){c=await BlobToImage(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const f=c.getBoundingClientRect();document.body.removeChild(c);
return[f.width,f.height]}};self.C3_RasterSvgImageBlob=async function(c,f,m,l,p){c=await BlobToSvgImage(c,f,m);const d=document.createElement("canvas");d.width=l;d.height=p;d.getContext("2d").drawImage(c,0,0,f,m);return d};let u=!1;document.addEventListener("pause",()=>u=!0);document.addEventListener("resume",()=>u=!1);a.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=
this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;c.AddRuntimeComponentMessageHandler("canvas","update-size",l=>this._OnUpdateCanvasSize(l));c.AddRuntimeComponentMessageHandler("runtime","invoke-download",l=>this._OnInvokeDownload(l));c.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",l=>this._OnRasterSvgImage(l));c.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",l=>this._OnGetSvgImageSize(l));
c.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",l=>this._OnSetTargetOrientation(l));c.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());c.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",l=>this._OnPostToDebugger(l));c.AddRuntimeComponentMessageHandler("runtime","go-to-script",l=>this._OnPostToDebugger(l));c.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());c.AddRuntimeComponentMessageHandler("runtime",
"debug-highlight",l=>this._OnDebugHighlight(l));c.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());c.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());c.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",l=>this._OnAddStylesheet(l));c.AddRuntimeComponentMessageHandler("runtime","alert",l=>this._OnAlert(l));c.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",
()=>this._OnHideCordovaSplash());const f=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const p=l.target,d=p.tagName.toLowerCase();f.has(d)||IsInContentEditable(p)||l.preventDefault()});const m=c.GetCanvas();window.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);window.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);m.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);m.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);
window.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc,{passive:!1}),m.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc)):m.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc);this._mousePointerLastButtons=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",BlockWheelZoom,{passive:!1});window.addEventListener("wheel",
BlockWheelZoom,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());c.IsiOSWebView()&&window.addEventListener("focusout",()=>{KeyboardIsVisible()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):
document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!u)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:ParentHasFocus()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("webkitfullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("mozfullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("keydown",f=>this._OnKeyEvent("keydown",f));window.addEventListener("keyup",f=>this._OnKeyEvent("keyup",f));window.addEventListener("dblclick",f=>this._OnMouseEvent("dblclick",
f,e));window.addEventListener("wheel",f=>this._OnMouseWheelEvent("wheel",f));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",f=>{this._HandlePointerDownFocus(f);this._OnPointerEvent("pointerdown",f)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",
f=>this._OnPointerRawUpdate(f))):window.addEventListener("pointermove",f=>this._OnPointerEvent("pointermove",f)),window.addEventListener("pointerup",f=>this._OnPointerEvent("pointerup",f)),window.addEventListener("pointercancel",f=>this._OnPointerEvent("pointercancel",f))):(window.addEventListener("mousedown",f=>{this._HandlePointerDownFocus(f);this._OnMouseEventAsPointer("pointerdown",f)}),window.addEventListener("mousemove",f=>this._OnMouseEventAsPointer("pointermove",f)),window.addEventListener("mouseup",
f=>this._OnMouseEventAsPointer("pointerup",f)),window.addEventListener("touchstart",f=>{this._HandlePointerDownFocus(f);this._OnTouchEvent("pointerdown",f)}),window.addEventListener("touchmove",f=>this._OnTouchEvent("pointermove",f)),window.addEventListener("touchend",f=>this._OnTouchEvent("pointerup",f)),window.addEventListener("touchcancel",f=>this._OnTouchEvent("pointercancel",f)));const c=()=>this._PlayPendingMedia();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",
c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}_PostRuntimeEvent(c,f){this.PostToRuntime(c,f||null,t)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_OnWindowResize(){const c=this._GetWindowInnerWidth(),f=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:c,innerHeight:f,devicePixelRatio:window.devicePixelRatio});
this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(c,f,0))}_ScheduleSimulatedResize(c,f,m){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(c,f,m),48)}_OnSimulatedResize(c,f,m){const l=this._GetWindowInnerWidth(),p=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;l!=c||p!=f?this._PostRuntimeEvent("window-resize",
{innerWidth:l,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>m&&this._ScheduleSimulatedResize(l,p,m+1)}_OnSetTargetOrientation(c){this._targetOrientation=c.targetOrientation}_TrySetTargetOrientation(){const c=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(c):screen.webkitLockOrientation?f=screen.webkitLockOrientation(c):
screen.mozLockOrientation?f=screen.mozLockOrientation(c):screen.msLockOrientation&&(f=screen.msLockOrientation(c));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}_OnFullscreenChange(){const c=a.IsDocumentFullscreen();c&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:c,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(c){console.warn("[Construct 3] Fullscreen request failed: ",
c);this.PostToRuntime("fullscreenerror",{isFullscreen:a.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(c){c?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:c})}_OnKeyEvent(c,f){"Backspace"===f.key&&PreventDefaultOnCanvasOrDoc(f);const m=b.get(f.code)||f.code;this._PostToRuntimeMaybeSync(c,{code:m,key:f.key,which:f.which,repeat:f.repeat,altKey:f.altKey,
ctrlKey:f.ctrlKey,metaKey:f.metaKey,shiftKey:f.shiftKey,timeStamp:f.timeStamp},e)}_OnMouseWheelEvent(c,f){this.PostToRuntime(c,{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},e)}_OnMouseEvent(c,f,m){IsCompatibilityMouseEvent(f)||this._PostToRuntimeMaybeSync(c,{button:f.button,buttons:f.buttons,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,timeStamp:f.timeStamp},m)}_OnMouseEventAsPointer(c,
f){if(!IsCompatibilityMouseEvent(f)){var m=this._mousePointerLastButtons;"pointerdown"===c&&0!==m?c="pointermove":"pointerup"===c&&0!==f.buttons&&(c="pointermove");this._PostToRuntimeMaybeSync(c,{pointerId:1,pointerType:"mouse",button:f.button,buttons:f.buttons,lastButtons:m,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:f.timeStamp},e);this._mousePointerLastButtons=f.buttons;this._OnMouseEvent(f.type,
f,k)}}_OnPointerEvent(c,f){this._pointerRawUpdateRateLimiter&&"pointermove"!==c&&this._pointerRawUpdateRateLimiter.Reset();var m=0;"mouse"===f.pointerType&&(m=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(c,{pointerId:f.pointerId,pointerType:f.pointerType,button:f.button,buttons:f.buttons,lastButtons:m,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:f.width||0,height:f.height||0,pressure:f.pressure||0,tangentialPressure:f.tangentialPressure||0,tiltX:f.tiltX||0,
tiltY:f.tiltY||0,twist:f.twist||0,timeStamp:f.timeStamp},e);"mouse"===f.pointerType&&(m="mousemove","pointerdown"===c?m="mousedown":"pointerup"===c&&(m="pointerup"),this._OnMouseEvent(m,f,k),this._mousePointerLastButtons=f.buttons)}_OnPointerRawUpdate(c){this._lastPointerRawUpdateEvent=c;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(c,f){for(let m=0,l=f.changedTouches.length;m<
l;++m){const p=f.changedTouches[m];this._PostToRuntimeMaybeSync(c,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:f.timeStamp},e)}}_HandlePointerDownFocus(c){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(c.target)&&
document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",c=>this._OnDeviceOrientation(c)),window.addEventListener("deviceorientationabsolute",c=>this._OnDeviceOrientationAbsolute(c)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||
(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",c=>this._OnDeviceMotion(c)))}_OnDeviceOrientation(c){this.PostToRuntime("deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},e)}_OnDeviceOrientationAbsolute(c){this.PostToRuntime("deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||
0,timeStamp:c.timeStamp},e)}_OnDeviceMotion(c){let f=null;var m=c.acceleration;m&&(f={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var l=c.accelerationIncludingGravity;l&&(m={x:l.x||0,y:l.y||0,z:l.z||0});l=null;const p=c.rotationRate;p&&(l={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});this.PostToRuntime("devicemotion",{acceleration:f,accelerationIncludingGravity:m,rotationRate:l,interval:c.interval,timeStamp:c.timeStamp},e)}_OnUpdateCanvasSize(c){const f=this.GetRuntimeInterface(),m=f.GetCanvas();m.style.width=
c.styleWidth+"px";m.style.height=c.styleHeight+"px";m.style.marginLeft=c.marginLeft+"px";m.style.marginTop=c.marginTop+"px";f.MaybeForceBodySize();this._isFirstSizeUpdate&&(m.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(c){const f=c.url;c=c.filename;const m=document.createElement("a"),l=document.body;m.textContent=c;m.href=f;m.download=c;l.appendChild(m);m.click();l.removeChild(m)}async _OnRasterSvgImage(c){var f=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,
c.imageHeight,c.surfaceWidth,c.surfaceHeight);f=f?await createImageBitmap(c,f):await createImageBitmap(c);return{imageBitmap:f,transferables:[f]}}async _OnGetSvgImageSize(c){return await self.C3_GetSvgImageSize(c.blob)}async _OnAddStylesheet(c){await AddStyleSheet(c.url)}_PlayPendingMedia(){var c=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const f of c)(c=f.play())&&c.catch(m=>{this._mediaRemovedPendingPlay.has(f)||this._mediaPendingPlay.add(f)})}TryPlayMedia(c){if("function"!==
typeof c.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(c);let f;try{f=c.play()}catch(m){this._mediaPendingPlay.add(c);return}f&&f.catch(m=>{this._mediaRemovedPendingPlay.has(c)||this._mediaPendingPlay.add(c)})}RemovePendingPlay(c){this._mediaPendingPlay.delete(c);this._mediaRemovedPendingPlay.add(c)}SetSilent(c){this._isSilent=!!c}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(c){if(c.show){this._debugHighlightElem||
(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var f=this._debugHighlightElem;f.style.display="";f.style.left=c.left-1+"px";f.style.top=c.top-1+"px";f.style.width=c.width+2+"px";f.style.height=c.height+2+"px";f.textContent=c.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(c){window.c3_postToMessagePort&&
(c.from="runtime",window.c3_postToMessagePort(c))}_InvokeFunctionFromJS(c,f){return this.PostToRuntimeAsync("js-invoke-function",{name:c,params:f})}_OnAlert(c){alert(c.message)}})}"use strict";
{const a=document.currentScript.src;self.JobSchedulerDOM=class{constructor(b){this._runtimeInterface=b;this._baseUrl=a?a.substr(0,a.lastIndexOf("/")+1):b.GetBaseURL();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var b=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=await this._runtimeInterface.CreateWorker(b,
this._baseUrl,{name:"DispatchWorker"});b=new MessageChannel;this._inputPort=b.port1;this._dispatchWorker.postMessage({type:"_init","in-port":b.port2},[b.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const b=this._jobWorkers.length;var e=this._runtimeInterface._GetWorkerURL("jobworker.js");e=await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"JobWorker"+b});const k=new MessageChannel,t=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:k.port1},[k.port1]);e.postMessage({type:"init",number:b,"dispatch-port":k.port2,"output-port":t.port2},[k.port2,t.port2]);this._jobWorkers.push(e);return t.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:"undefined"!==typeof OffscreenCanvas,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"user-media");this.SetAutoAttach(!1);this._isRuntimeInWorker=this._iRuntime.UsesWorker();this._sequenceNumber=0;this._lastActiveStream=null;this.AddRuntimeMessageHandler("get-media-sources",()=>this._OnGetMediaSources());this.AddDOMElementMessageHandler("request-camera",(b,e)=>this._OnRequestCamera(b,e));this.AddDOMElementMessageHandler("request-microphone",(b,e)=>this._OnRequestMicrophone(b,e));this.AddDOMElementMessageHandler("snapshot",
(b,e)=>this._Snapshot(b,e));this.AddDOMElementMessageHandler("stop",b=>this._Stop(b));self.C3UserMedia_GetVideoElement=b=>this.GetElementById(b);self.C3UserMedia_GetLastMediaStream=()=>this._lastActiveStream}CreateElement(a,b){const e=document.createElement("video");e.crossOrigin="anonymous";e.autoplay=!0;e.muted=!0;e.playsInline=!0;e.addEventListener("canplaythrough",()=>{this.PostToRuntimeElement("video-ready",a,{width:e.videoWidth,height:e.videoHeight})});return e}UpdateState(a,b){}DestroyElement(a){a.srcObject&&
(this._StopStream(a.srcObject),a.srcObject=null)}_StopStream(a){this._lastActiveStream===a&&(this._lastActiveStream=null);a=a.getTracks();for(let b=0,e=a.length;b<e;++b)a[b].stop()}async _OnGetMediaSources(){const a=[],b=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var e=await navigator.mediaDevices.enumerateDevices();for(const k of e){e=k.kind;const t={deviceId:k.deviceId,label:k.label,facing:k.facing||k.facingMode||""};"video"===e||"videoinput"===e?a.push(t):("audio"===
e||"audioinput"===e)&&b.push(t)}}return{videoSources:a,audioSources:b}}async _OnRequestCamera(a,b){try{const e="object"===typeof b.constraints.audio,k=this.GetRuntimeInterface();e?await k.RequirePermissions("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await k.RequirePermissions("CAMERA");this._lastActiveStream=await navigator.mediaDevices.getUserMedia(b.constraints);a.srcObject=this._lastActiveStream;a.play();this._isRuntimeInWorker&&this._StartTicking();return{ok:!0}}catch(e){return console.warn("Error requesting camera: ",
e),{ok:!1}}}async _OnRequestMicrophone(a,b){try{return await this.GetRuntimeInterface().RequirePermissions("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),this._lastActiveStream=await navigator.mediaDevices.getUserMedia(b.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(this._lastActiveStream,b.tag),{ok:!0}}catch(e){return console.warn("Error requesting microphone: ",e),{ok:!1}}}_CanvasToURL(a,b,e){return new Promise((k,t)=>{a.toBlob?a.toBlob(q=>k(URL.createObjectURL(q)),b,e):
k(a.toDataURL(b,e))})}async _Snapshot(a,b){const e=document.createElement("canvas");e.width=a.videoWidth;e.height=a.videoHeight;e.getContext("2d").drawImage(a,0,0,a.videoWidth,a.videoHeight);return{snapshotUrl:await this._CanvasToURL(e,b.format,b.quality)}}_Stop(a){a.srcObject&&(this._StopStream(a.srcObject),a.srcObject=null)}Tick(){if(this._isRuntimeInWorker){var a={},b={sequenceNumber:this._sequenceNumber++,videoData:a},e=[],k=[];for(const [t,q]of this._elementMap.entries()){if(!q.srcObject)continue;
const u={};k.push(createImageBitmap(q).then(c=>{u.imageBitmap=c;e.push(c)}).catch(c=>{u.imageBitmap=null}));a[t.toString()]=u}Promise.all(k).then(()=>this.PostToRuntime("state",b,!1,e))}}});"use strict";var StopPropagation=function(a){a.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"button")}CreateElement(a,b){const e=document.createElement("input");var k=e;b.isCheckbox?(e.type="checkbox",k=document.createElement("label"),k.appendChild(e),k.appendChild(document.createTextNode("")),k.style.fontFamily="sans-serif",k.style.userSelect="none",k.style.webkitUserSelect="none",k.style.display="inline-block",k.style.color="black"):e.type="button";k.style.position="absolute";k.addEventListener("touchstart",
StopPropagation);k.addEventListener("touchmove",StopPropagation);k.addEventListener("touchend",StopPropagation);k.addEventListener("mousedown",StopPropagation);k.addEventListener("mouseup",StopPropagation);k.addEventListener("keydown",StopPropagation);k.addEventListener("keyup",StopPropagation);e.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",a,{isChecked:e.checked}));b.id&&(e.id=b.id);this.UpdateState(k,b);return k}_GetInputElem(a){return"input"===a.tagName.toLowerCase()?
a:a.firstChild}UpdateState(a,b){const e=this._GetInputElem(a);e.checked=b.isChecked;e.disabled=!b.isEnabled;a.title=b.title;a===e?e.value=b.text:a.lastChild.textContent=b.text}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",b=>this._OnGetInitialState(b)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",b=>this._OnAlert(b)],["close",()=>this._OnClose()],["set-focus",b=>this._OnSetFocus(b)],["vibrate",b=>this._OnVibrate(b)],["lock-orientation",b=>this._OnLockOrientation(b)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",b=>this._OnNavigate(b)],["request-fullscreen",b=>this._OnRequestFullscreen(b)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",b=>this._OnSetHash(b)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
b=>this._OnWin10BackRequested(b))}_OnGetInitialState(a){this._exportType=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>
this.PostToRuntime("sw-message",a.data))}_OnOnlineStateChanged(a){this.PostToRuntime("online-state",{isOnline:a})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(a){a.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(a){alert(a.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(a){a=
a.isFocus;if("nwjs"===this._exportType){const b=this.GetNWjsWindow();a?b.focus():b.blur()}else a?window.focus():window.blur()}_OnVibrate(a){navigator.vibrate&&navigator.vibrate(a.pattern)}_OnLockOrientation(a){a=a.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct 3] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):
screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}_OnNavigate(a){var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var e=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this._isScirraArcade||(2===e?window.top.location=b:1===e?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,e=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,e))}_OnRequestFullscreen(a){const b={navigationUI:"auto"};
a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}_OnExitFullscreen(){document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}_OnSetHash(a){location.hash=a.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";var StopPropagation$jscomp$1=function(a){a.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"list");this.AddDOMElementMessageHandler("set-selected-index",(b,e)=>this._OnSetSelectedIndex(b,e.selectedIndex));this.AddDOMElementMessageHandler("add-item",(b,e)=>this._OnAddItem(b,e));this.AddDOMElementMessageHandler("remove-item",(b,e)=>this._OnRemoveItem(b,e));this.AddDOMElementMessageHandler("set-item",(b,e)=>this._OnSetItem(b,e));this.AddDOMElementMessageHandler("clear",b=>this._OnClear(b));
this.AddDOMElementMessageHandler("load-state",(b,e)=>this._OnLoadState(b,e))}CreateElement(a,b){const e=b.isDropdown,k=b.isMultiSelect,t=b.items,q=document.createElement("select");q.style.position="absolute";q.style.userSelect="none";q.style.webkitUserSelect="none";q.multiple=k;e||(q.size=2);for(const u of t)q.add(this._CreateOption(u));q.addEventListener("touchstart",StopPropagation$jscomp$1);q.addEventListener("touchmove",StopPropagation$jscomp$1);q.addEventListener("touchend",StopPropagation$jscomp$1);
q.addEventListener("mousedown",StopPropagation$jscomp$1);q.addEventListener("mouseup",StopPropagation$jscomp$1);q.addEventListener("click",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("click",a,this._GetSelectionState(q))});q.addEventListener("dblclick",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",a,this._GetSelectionState(q))});q.addEventListener("change",()=>this.PostToRuntimeElement("change",a,this._GetSelectionState(q)));b.id&&(q.id=b.id);this.UpdateState(q,
b);return q}_CreateOption(a){const b=document.createElement("option");b.text=a;return b}_GetSelectionState(a){const b=a.selectedIndex,e=[];for(let k=0,t=a.length;k<t;++k)a.options[k].selected&&e.push(k);return{selectedIndex:b,selectedIndices:e}}UpdateState(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}_OnSetSelectedIndex(a,b){a.selectedIndex=b}_OnAddItem(a,b){const e=b.index;b=this._CreateOption(b.text);0>e?a.add(b):a.add(b,e)}_OnRemoveItem(a,b){a.remove(b.index)}_OnSetItem(a,
b){a.options[b.index].text=b.text}_OnClear(a){a.innerHTML=""}_OnLoadState(a,b){a.innerHTML="";for(const e of b.items)a.add(this._CreateOption(e));a.selectedIndex=b.selectedIndex;for(const e of b.selectedIndices)if(b=a.options[e])b.selected=!0}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"game-recorder");this._mediaStream=this._mediaRecorder=null;this._stopStreamOnEnd=!0;this._recordedChunks=[];this._lastRecordingUrl="";this.AddRuntimeMessageHandler("get-supported-formats",()=>this._OnGetSupportedFormats());this.AddRuntimeMessageHandler("start-recording",b=>this._OnStartRecording(b));this.AddRuntimeMessageHandler("start-screen-recording",b=>this._OnStartScreenRecording(b));this.AddRuntimeMessageHandler("start-user-media-recording",
b=>this._OnStartUserMediaRecording(b));this.AddRuntimeMessageHandler("stop-recording",()=>this._OnStopRecording());this._MaybePolyfillGetDisplayMedia()}_MaybePolyfillGetDisplayMedia(){navigator.mediaDevices&&navigator.mediaDevices.getDisplayMedia||navigator.mediaDevices&&navigator.mediaDevices.getSupportedConstraints&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getSupportedConstraints().mediaSource&&(navigator.mediaDevices.getDisplayMedia=function(){return navigator.mediaDevices.getUserMedia({video:{mediaSource:"screen"}})})}_OnGetSupportedFormats(){var a=
this._iRuntime.GetCanvas();const b="undefined"!==typeof MediaRecorder;a=!(!a.captureStream||!b);const e=[],k=[];a&&(MediaRecorder.isTypeSupported("video/webm;codecs=vp8")&&e.push("video/webm;codecs=vp8"),MediaRecorder.isTypeSupported("video/webm;codecs=vp9")&&e.push("video/webm;codecs=vp9"),MediaRecorder.isTypeSupported("audio/ogg;codecs=opus")&&k.push("audio/ogg;codecs=opus"),MediaRecorder.isTypeSupported("audio/webm;codecs=opus")&&k.push("audio/webm;codecs=opus"));return{isSupported:a,isMediaRecorderSupported:b,
isScreenRecordingSupported:!(!navigator.mediaDevices||!navigator.mediaDevices.getDisplayMedia||"undefined"===typeof MediaRecorder),supportedVideoFormats:e,supportedAudioFormats:k}}_StopStreamVideoTracks(a){a=a.getTracks();for(let b=0,e=a.length;b<e;++b){const k=a[b];"video"===k.kind&&k.stop()}}_StopAnyPriorRecording(){this._OnStopRecording();this._recordedChunks.length=0;this._lastRecordingUrl&&(URL.revokeObjectURL(this._lastRecordingUrl),this._lastRecordingUrl="")}_OnStartRecording(a){const b=a.videoType,
e=a.audioType,k=a.bitsPerSecond;a=a.framerate;this._StopAnyPriorRecording();let t=[],q=[];try{if(b){const u=this._iRuntime.GetCanvas();t=(0<a?u.captureStream(a):u.captureStream()).getVideoTracks()}e&&self.C3Audio_GetOutputStream&&(q=self.C3Audio_GetOutputStream().getAudioTracks());this._mediaStream=new MediaStream([...t,...q]);this._stopStreamOnEnd=!0;this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:b||e,bitsPerSecond:k})}catch(u){console.error("[Game Recorder] Failed to start recording: ",
u),this.PostToRuntime("error")}this._StartMediaRecorder(b,e)}async _OnStartScreenRecording(a){const b=a.videoType,e=a.audioType;a=a.bitsPerSecond;this._StopAnyPriorRecording();let k=[],t=[];try{b&&(k=(await navigator.mediaDevices.getDisplayMedia({video:!0})).getVideoTracks()),e&&self.C3Audio_GetOutputStream&&(t=self.C3Audio_GetOutputStream().getAudioTracks()),this._mediaStream=new MediaStream([...k,...t]),this._stopStreamOnEnd=!0,this._mediaStream.addEventListener("inactive",()=>this._OnMediaStreamInactive()),
this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:b||e,bitsPerSecond:a})}catch(q){console.error("[Game Recorder] Failed to start recording: ",q),this.PostToRuntime("error")}this._StartMediaRecorder(b,e)}async _OnStartUserMediaRecording(a){const b=a.videoType,e=a.audioType;a=a.bitsPerSecond;this._StopAnyPriorRecording();if(self.C3UserMedia_GetLastMediaStream){var k=self.C3UserMedia_GetLastMediaStream();if(k){try{this._mediaStream=k,this._stopStreamOnEnd=!1,this._mediaRecorder=new MediaRecorder(this._mediaStream,
{mimeType:b||e,bitsPerSecond:a})}catch(t){console.error("[Game Recorder] Failed to start recording: ",t),this.PostToRuntime("error")}this._StartMediaRecorder(b,e)}}}_StartMediaRecorder(a,b){this._mediaRecorder.ondataavailable=e=>{this._recordedChunks.push(e.data)};this._mediaRecorder.onerror=e=>{console.error("[Game Recorder] Error recording: ",e);this.PostToRuntime("error")};this._mediaRecorder.onwarning=e=>{console.warn("[Game Recorder] Recording warning: ",e)};this._mediaRecorder.onstop=e=>{e=
new Blob(this._recordedChunks,{type:a||b});this._lastRecordingUrl=URL.createObjectURL(e);this.PostToRuntime("recording-ready",{url:this._lastRecordingUrl})};this._mediaRecorder.start()}_OnMediaStreamInactive(){this.PostToRuntime("screen-recording-stopped");this._OnStopRecording()}_OnStopRecording(){this._mediaRecorder&&(this._mediaRecorder.stop(),this._mediaRecorder=null);this._mediaStream&&(this._stopStreamOnEnd&&this._StopStreamVideoTracks(this._mediaStream),this._mediaStream=null)}});"use strict";
var StopKeyPropagation=function(a){13!==a.which&&27!==a.which&&a.stopPropagation()},StopPropagation$jscomp$2=function(a){a.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",b=>this._OnScrollToBottom(b))}CreateElement(a,b){let e;const k=b.type;"textarea"===k?(e=document.createElement("textarea"),e.style.resize="none"):(e=document.createElement("input"),e.type=k);e.style.position="absolute";e.autocomplete="off";e.addEventListener("touchstart",StopPropagation$jscomp$2);e.addEventListener("touchmove",StopPropagation$jscomp$2);
e.addEventListener("touchend",StopPropagation$jscomp$2);e.addEventListener("mousedown",StopPropagation$jscomp$2);e.addEventListener("mouseup",StopPropagation$jscomp$2);e.addEventListener("keydown",StopKeyPropagation);e.addEventListener("keyup",StopKeyPropagation);e.addEventListener("click",t=>{t.stopPropagation();this._PostToRuntimeElementMaybeSync("click",a)});e.addEventListener("dblclick",t=>{t.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",a)});e.addEventListener("input",()=>
this.PostToRuntimeElement("change",a,{text:e.value}));b.id&&(e.id=b.id);this.UpdateState(e,b);return e}UpdateState(a,b){a.value=b.text;a.placeholder=b.placeholder;a.title=b.title;a.disabled=!b.isEnabled;a.readOnly=b.isReadOnly;a.spellcheck=b.spellCheck;b=b.maxLength;0>b?a.removeAttribute("maxlength"):a.setAttribute("maxlength",b)}_OnScrollToBottom(a){a.scrollTop=a.scrollHeight}});"use strict";var StopPropagation$jscomp$3=function(a){a.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"sliderbar")}CreateElement(a,b){const e=document.createElement("input");e.type="range";e.style.position="absolute";e.style.userSelect="none";e.style.webkitUserSelect="none";e.addEventListener("touchstart",StopPropagation$jscomp$3);e.addEventListener("touchmove",StopPropagation$jscomp$3);e.addEventListener("touchend",StopPropagation$jscomp$3);e.addEventListener("mousedown",StopPropagation$jscomp$3);
e.addEventListener("mouseup",StopPropagation$jscomp$3);e.addEventListener("keydown",StopPropagation$jscomp$3);e.addEventListener("keyup",StopPropagation$jscomp$3);e.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",a));e.addEventListener("change",()=>this.PostToRuntimeElement("change",a,{value:parseFloat(e.value)}));e.addEventListener("input",()=>this.PostToRuntimeElement("input",a,{value:parseFloat(e.value)}));b.id&&(e.id=b.id);this.UpdateState(e,b);return e}UpdateState(a,
b){a.max=b.max;a.min=b.min;a.step=b.step;a.value=b.value;a.disabled=!b.isEnabled;a.title=b.title}});