'use strict';window.DOMHandler=class{constructor(b,c){this._iRuntime=b;this._componentId=c;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(b,c,e,g){this._iRuntime.PostToRuntimeComponent(this._componentId,b,c,e,g)}PostToRuntimeAsync(b,c,e,g){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,b,c,e,g)}_PostToRuntimeMaybeSync(b,c,e){this._iRuntime.UsesWorker()?this.PostToRuntime(b,c,e):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:b,dispatchOpts:e||null,data:c,responseId:null})}AddRuntimeMessageHandler(b,c){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,b,c)}AddRuntimeMessageHandlers(b){for(const [c,e]of b)this.AddRuntimeMessageHandler(c,e)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(b,c){this._callback=b;this._interval=c;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(b){this._canRunImmediate=!!b}Call(){if(-1===this._timerId){var b=Date.now(),c=b-this._lastCallTime,e=this._interval;c>=e&&this._canRunImmediate?(this._lastCallTime=b,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(e-c,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(b,c){super(b,c);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",e=>this._OnCreate(e)],["destroy",e=>this._OnDestroy(e)],["set-visible",e=>this._OnSetVisible(e)],["update-position",e=>this._OnUpdatePosition(e)],["update-state",e=>this._OnUpdateState(e)],["focus",e=>this._OnSetFocus(e)],["set-css-style",e=>this._OnSetCssStyle(e)],["set-attribute",e=>this._OnSetAttribute(e)],["remove-attribute",
e=>this._OnRemoveAttribute(e)]]);this.AddDOMElementMessageHandler("get-element",e=>e)}SetAutoAttach(b){this._autoAttach=!!b}AddDOMElementMessageHandler(b,c){this.AddRuntimeMessageHandler(b,e=>{const g=this._elementMap.get(e.elementId);return c(g,e)})}_OnCreate(b){const c=b.elementId,e=this.CreateElement(c,b);this._elementMap.set(c,e);b.isVisible||(e.style.display="none");b=this._GetFocusElement(e);b.addEventListener("focus",g=>this._OnFocus(c));b.addEventListener("blur",g=>this._OnBlur(c));this._autoAttach&&
document.body.appendChild(e)}CreateElement(b,c){throw Error("required override");}DestroyElement(b){}_OnDestroy(b){b=b.elementId;const c=this._elementMap.get(b);this.DestroyElement(c);this._autoAttach&&c.parentElement.removeChild(c);this._elementMap.delete(b)}PostToRuntimeElement(b,c,e){e||(e={});e.elementId=c;this.PostToRuntime(b,e)}_PostToRuntimeElementMaybeSync(b,c,e){e||(e={});e.elementId=c;this._PostToRuntimeMaybeSync(b,e)}_OnSetVisible(b){this._autoAttach&&(this._elementMap.get(b.elementId).style.display=
b.isVisible?"":"none")}_OnUpdatePosition(b){if(this._autoAttach){var c=this._elementMap.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}_OnUpdateState(b){const c=this._elementMap.get(b.elementId);this.UpdateState(c,b)}UpdateState(b,c){throw Error("required override");}_GetFocusElement(b){return b}_OnFocus(b){this.PostToRuntimeElement("elem-focused",b)}_OnBlur(b){this.PostToRuntimeElement("elem-blurred",
b)}_OnSetFocus(b){const c=this._GetFocusElement(this._elementMap.get(b.elementId));b.focus?c.focus():c.blur()}_OnSetCssStyle(b){this._elementMap.get(b.elementId).style[b.prop]=b.val}_OnSetAttribute(b){this._elementMap.get(b.elementId).setAttribute(b.name,b.val)}_OnRemoveAttribute(b){this._elementMap.get(b.elementId).removeAttribute(b.name)}GetElementById(b){return this._elementMap.get(b)}};"use strict";
{const b=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function c(r){if(r.isStringSrc){const f=document.createElement("script");f.async=!1;f.textContent=r.str;document.head.appendChild(f)}else return new Promise((f,h)=>{const a=document.createElement("script");a.onload=f;a.onerror=h;a.async=!1;a.src=r;document.head.appendChild(a)})}let e=new Audio;const g={"audio/webm; codecs=opus":!!e.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!e.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!e.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!e.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!e.canPlayType("audio/mp4"),"audio/mpeg":!!e.canPlayType("audio/mpeg")};e=null;async function m(r){r=await q(r);return(new TextDecoder("utf-8")).decode(r)}function q(r){return new Promise((f,h)=>{const a=new FileReader;a.onload=d=>f(d.target.result);a.onerror=d=>h(d);a.readAsArrayBuffer(r)})}const p=[];let u=0;window.RealFile=window.File;const w=
[],x=new Map,y=new Map;let A=0;const B=[];self.runOnStartup=function(r){if("function"!==typeof r)throw Error("runOnStartup called without a function");B.push(r)};const v=new Set(["cordova","playable-ad","instant-games"]);function z(r){return v.has(r)}window.RuntimeInterface=class r{constructor(f){this._useWorker=f.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=f.scriptFolder;this._workerScriptBlobURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=
this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=f.exportType;z(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._transferablesBroken=!1;this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,
4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",h=>this._OnCordovaFetchLocalFile(h));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",h=>this._OnCreateJobWorker(h));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(f)):this._Init(f)}Release(){this._CancelAnimationFrame();
this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsiOSCordova(){return b&&"cordova"===this._exportType}IsiOSWebView(){return b&&
z(this._exportType)||navigator.standalone}async _Init(f){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let a=0,d=f.engineScripts.length;a<d;++a){var h=f.engineScripts[a].toLowerCase();this._localFileStrings.hasOwnProperty(h)?f.engineScripts[a]={isStringSrc:!0,str:this._localFileStrings[h]}:this._localFileBlobs.hasOwnProperty(h)&&(f.engineScripts[a]=URL.createObjectURL(this._localFileBlobs[h]))}}f.baseUrl?
this._baseUrl=f.baseUrl:(h=location.origin,this._baseUrl=("null"===h?"file:///":h)+location.pathname,h=this._baseUrl.lastIndexOf("/"),-1!==h&&(this._baseUrl=this._baseUrl.substr(0,h+1)));if(f.workerScripts)for(const [a,d]of Object.entries(f.workerScripts))this._workerScriptBlobURLs[a]=URL.createObjectURL(d);h=new MessageChannel;this._messageChannelPort=h.port1;this._messageChannelPort.onmessage=a=>this._OnMessageFromRuntime(a.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>
this._OnMessageFromDebugger(a));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this._TestTransferablesWork();this._useWorker?await this._InitWorker(f,h.port2):await this._InitDOM(f,h.port2)}_GetWorkerURL(f){return this._workerScriptBlobURLs.hasOwnProperty(f)?this._workerScriptBlobURLs[f]:
f.endsWith("/workermain.js")&&this._workerScriptBlobURLs.hasOwnProperty("workermain.js")?this._workerScriptBlobURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this._localFileBlobs[f.toLowerCase()]):f}async CreateWorker(f,h,a){if(f.startsWith("blob:"))return new Worker(f,a);if(this.IsiOSCordova()&&"file:"===location.protocol)return f=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+f),f=new Blob([f],{type:"application/javascript"}),
new Worker(URL.createObjectURL(f),a);f=new URL(f,h);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),a)}return new Worker(f,a)}MaybeForceBodySize(){if(this.IsiOSWebView()){const f=document.documentElement.style,h=document.body.style,a=window.innerWidth<window.innerHeight,d=a?window.screen.width:window.screen.height;h.height=f.height=(a?window.screen.height:window.screen.width)+"px";h.width=
f.width=d+"px"}}_GetCommonRuntimeOptions(f){return{baseUrl:this._baseUrl,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:r.IsDocumentFullscreen(),projectData:f.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),
supportedAudioFormats:g,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(f,h){var a=this._GetWorkerURL(f.workerMainUrl);this._worker=await this.CreateWorker(a,this._baseUrl,{name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display=
"none";a=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(f),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:a,workerDependencyScripts:f.workerDependencyScripts||[],engineScripts:f.engineScripts,projectScripts:window.cr_allProjectScripts,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,a,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=w.map(d=>
new d(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(d,k)=>this._runtimeDomHandler._InvokeFunctionFromJS(d,k);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(f,h){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=w.map(d=>new d(this));this._FindRuntimeDOMHandler();const a=f.engineScripts.map(d=>
"string"===typeof d?(new URL(d,this._baseUrl)).toString():d);Array.isArray(f.workerDependencyScripts)&&a.unshift(...f.workerDependencyScripts);await Promise.all(a.map(d=>c(d)));if(f.projectScripts&&0<f.projectScripts.length){const d=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.projectScripts.map(k=>c(k[1]))),Object.values(d).some(k=>!k)){self.setTimeout(()=>this._ReportProjectScriptError(d),100);return}}catch(k){console.error("[Preview] Error loading project scripts: ",k);self.setTimeout(()=>
this._ReportProjectScriptError(d),100);return}}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this._GetCommonRuntimeOptions(f),{isInWorker:!1,messagePort:h,canvas:this._canvas,runOnStartupFunctions:B}),this._localRuntime=self.C3_CreateRuntime(f),
await self.C3_InitRuntime(this._localRuntime,f))}_ReportProjectScriptError(f){f=`Failed to load project script '${Object.entries(f).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}async _OnCreateJobWorker(f){f=await this._jobScheduler._CreateJobWorker();return{outputPort:f,transferables:[f]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(f,
h,a,d,k){this._messageChannelPort.postMessage({type:"event",component:f,handler:h,dispatchOpts:d||null,data:a,responseId:null},this._transferablesBroken?void 0:k)}PostToRuntimeComponentAsync(f,h,a,d,k){const l=A++,n=new Promise((t,C)=>{y.set(l,{resolve:t,reject:C})});this._messageChannelPort.postMessage({type:"event",component:f,handler:h,dispatchOpts:d||null,data:a,responseId:l},this._transferablesBroken?void 0:k);return n}["_OnMessageFromRuntime"](f){const h=f.type;if("event"===h)return this._OnEventFromRuntime(f);
if("result"===h)this._OnResultFromRuntime(f);else if("runtime-ready"===h)this._OnRuntimeReady();else if("alert"===h)alert(f.message);else throw Error(`unknown message '${h}'`);}_OnEventFromRuntime(f){const h=f.component,a=f.handler,d=f.data,k=f.responseId;if(f=x.get(h))if(f=f.get(a)){var l=null;try{l=f(d)}catch(n){console.error(`Exception in '${h}' handler '${a}':`,n);null!==k&&this._PostResultToRuntime(k,!1,""+n);return}if(null===k)return l;l&&l.then?l.then(n=>this._PostResultToRuntime(k,!0,n)).catch(n=>
{console.error(`Rejection from '${h}' handler '${a}':`,n);this._PostResultToRuntime(k,!1,""+n)}):this._PostResultToRuntime(k,!0,l)}else console.warn(`[DOM] No handler '${a}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}_PostResultToRuntime(f,h,a){let d;a&&a.transferables&&(d=a.transferables);this._messageChannelPort.postMessage({type:"result",responseId:f,isOk:h,result:a},d)}_OnResultFromRuntime(f){const h=f.responseId,a=f.isOk;f=f.result;const d=y.get(h);
a?d.resolve(f):d.reject(f);y.delete(h)}AddRuntimeComponentMessageHandler(f,h,a){let d=x.get(f);d||(d=new Map,x.set(f,d));if(d.has(h))throw Error(`[DOM] Component '${f}' already has handler '${h}'`);d.set(h,a)}static AddDOMHandlerClass(f){if(w.includes(f))throw Error("DOM handler already added");w.push(f)}_FindRuntimeDOMHandler(){for(const f of this._domHandlers)if("runtime"===f.GetComponentID()){this._runtimeDomHandler=f;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(f){this.PostToRuntimeComponent("debugger",
"message",f)}_OnRuntimeReady(){for(const f of this._domHandlers)f.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(f){this._rafCallbacks.push(f);this._RequestAnimationFrame()}_RemoveRAFCallback(f){f=this._rafCallbacks.indexOf(f);if(-1===f)throw Error("invalid callback");
this._rafCallbacks.splice(f,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const f of this._rafCallbacks)f();this._RequestAnimationFrame()}TryPlayMedia(f){this._runtimeDomHandler.TryPlayMedia(f)}RemovePendingPlay(f){this._runtimeDomHandler.RemovePendingPlay(f)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(f){this._runtimeDomHandler.SetSilent(f)}IsAudioFormatSupported(f){return!!g[f]}async _WasmDecodeWebMOpus(f){f=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}IsAbsoluteURL(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}IsRelativeURL(f){return!this.IsAbsoluteURL(f)}async _OnCordovaFetchLocalFile(f){const h=f.filename;switch(f.as){case "text":return await this.CordovaFetchLocalFileAsText(h);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(h);default:throw Error("unsupported type");}}_GetPermissionAPI(){const f=
window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof f)throw Error("Permission API is not loaded");return f}_MapPermissionID(f,h){f=f[h];if("string"!==typeof f)throw Error("Invalid permission name");return f}_HasPermission(f){const h=this._GetPermissionAPI();return new Promise((a,d)=>h.checkPermission(this._MapPermissionID(h,f),k=>a(!!k.hasPermission),d))}_RequestPermission(f){const h=this._GetPermissionAPI();return new Promise((a,d)=>h.requestPermission(this._MapPermissionID(h,
f),k=>a(!!k.hasPermission),d))}async RequestPermissions(f){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const h of f)if(!await this._HasPermission(h)&&!1===await this._RequestPermission(h))return!1;return!0}async RequirePermissions(...f){if(!1===await this.RequestPermissions(f))throw Error("Permission not granted");}CordovaFetchLocalFile(f){const h=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((a,d)=>{window.resolveLocalFileSystemURL(h,
k=>{k.file(a,d)},d)})}async CordovaFetchLocalFileAsText(f){f=await this.CordovaFetchLocalFile(f);return await m(f)}_CordovaMaybeStartNextArrayBufferRead(){if(p.length&&!(8<=u)){u++;var f=p.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(f.filename,f.successCallback,f.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(f){return new Promise((h,a)=>{p.push({filename:f,successCallback:d=>{u--;this._CordovaMaybeStartNextArrayBufferRead();h(d)},errorCallback:d=>{u--;this._CordovaMaybeStartNextArrayBufferRead();
a(d)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(f,h,a){try{const d=await this.CordovaFetchLocalFile(f),k=await q(d);h(k)}catch(d){a(d)}}async _ConvertDataUrisToBlobs(){const f=[];for(const [h,a]of Object.entries(this._localFileBlobs))f.push(this._ConvertDataUriToBlobs(h,a));await Promise.all(f)}async _ConvertDataUriToBlobs(f,h){if("object"===typeof h)this._localFileBlobs[f]=new Blob([h.str],{type:h.type}),this._localFileStrings[f]=h.str;else{let a=
await this._FetchDataUri(h);a||(a=this._DataURIToBinaryBlobSync(h));this._localFileBlobs[f]=a}}async _FetchDataUri(f){try{return await (await fetch(f)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",h),null}}_DataURIToBinaryBlobSync(f){f=this._ParseDataURI(f);return this._BinaryStringToBlob(f.data,f.mime_type)}_ParseDataURI(f){var h=
f.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var a=f.substring(5,h);f=f.substring(h+1);h=a.split(";");a=h[0]||"";const d=h[2];f="base64"===h[1]||"base64"===d?atob(f):decodeURIComponent(f);return{mime_type:a,data:f}}_BinaryStringToBlob(f,h){var a=f.length;let d=a>>2,k=new Uint8Array(a),l=new Uint32Array(k.buffer,0,d),n,t;for(t=n=0;n<d;++n)l[n]=f.charCodeAt(t++)|f.charCodeAt(t++)<<8|f.charCodeAt(t++)<<16|f.charCodeAt(t++)<<24;for(a&=3;a--;)k[t]=f.charCodeAt(t),++t;return new Blob([k],
{type:h})}_TestTransferablesWork(){let f=null;const h=new Promise(k=>f=k),a=new ArrayBuffer(1),d=new MessageChannel;d.port2.onmessage=k=>{k.data&&k.data.arrayBuffer||(this._transferablesBroken=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));f()};d.port1.postMessage({arrayBuffer:a},[a]);return h}}}"use strict";
{const b=self.RuntimeInterface;function c(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const e=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),g={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},m={dispatchUserScriptEvent:!0},q={dispatchRuntimeEvent:!0};function p(a){return new Promise((d,k)=>{const l=document.createElement("link");l.onload=()=>d(l);l.onerror=
n=>k(n);l.rel="stylesheet";l.href=a;document.head.appendChild(l)})}function u(a){return new Promise((d,k)=>{const l=new Image;l.onload=()=>d(l);l.onerror=n=>k(n);l.src=a})}async function w(a){a=URL.createObjectURL(a);try{return await u(a)}finally{URL.revokeObjectURL(a)}}function x(a){return new Promise((d,k)=>{let l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsText(a)})}async function y(a,d,k){if(!/firefox/i.test(navigator.userAgent))return await w(a);var l=await x(a);l=
(new DOMParser).parseFromString(l,"image/svg+xml");const n=l.documentElement;if(n.hasAttribute("width")&&n.hasAttribute("height")){const t=n.getAttribute("width"),C=n.getAttribute("height");if(!t.includes("%")&&!C.includes("%"))return await w(a)}n.setAttribute("width",d+"px");n.setAttribute("height",k+"px");l=(new XMLSerializer).serializeToString(l);a=new Blob([l],{type:"image/svg+xml"});return await w(a)}function A(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);
return!1}const B=new Set(["canvas","body","html"]);function v(a){const d=a.target.tagName.toLowerCase();B.has(d)&&a.preventDefault()}function z(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}self.C3_GetSvgImageSize=async function(a){a=await w(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const d=a.getBoundingClientRect();document.body.removeChild(a);return[d.width,d.height]}};
self.C3_RasterSvgImageBlob=async function(a,d,k,l,n){a=await y(a,d,k);const t=document.createElement("canvas");t.width=l;t.height=n;t.getContext("2d").drawImage(a,0,0,d,k);return t};let r=!1;document.addEventListener("pause",()=>r=!0);document.addEventListener("resume",()=>r=!1);function f(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}}function h(){const a=document.activeElement;if(!a)return!1;const d=a.tagName.toLowerCase(),k=new Set("email number password search tel text url".split(" "));
return"textarea"===d?!0:"input"===d?k.has(a.type.toLowerCase()||"text"):A(a)}b.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;a.AddRuntimeComponentMessageHandler("canvas","update-size",l=>this._OnUpdateCanvasSize(l));
a.AddRuntimeComponentMessageHandler("runtime","invoke-download",l=>this._OnInvokeDownload(l));a.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",l=>this._OnRasterSvgImage(l));a.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",l=>this._OnGetSvgImageSize(l));a.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",l=>this._OnSetTargetOrientation(l));a.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());a.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",l=>this._OnPostToDebugger(l));a.AddRuntimeComponentMessageHandler("runtime","go-to-script",l=>this._OnPostToDebugger(l));a.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());a.AddRuntimeComponentMessageHandler("runtime","debug-highlight",l=>this._OnDebugHighlight(l));a.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());a.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());a.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",l=>this._OnAddStylesheet(l));a.AddRuntimeComponentMessageHandler("runtime","alert",l=>this._OnAlert(l));a.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const d=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const n=l.target,t=n.tagName.toLowerCase();d.has(t)||A(n)||l.preventDefault()});const k=a.GetCanvas();window.addEventListener("selectstart",
v);window.addEventListener("gesturehold",v);k.addEventListener("selectstart",v);k.addEventListener("gesturehold",v);window.addEventListener("touchstart",v,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",v,{passive:!1}),k.addEventListener("pointerdown",v)):k.addEventListener("touchstart",v);this._mousePointerLastButtons=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",z,{passive:!1});window.addEventListener("wheel",
z,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());a.IsiOSWebView()&&window.addEventListener("focusout",()=>{h()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",
()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!r)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:f()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",
()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("webkitfullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("mozfullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("keydown",d=>this._OnKeyEvent("keydown",d));window.addEventListener("keyup",d=>this._OnKeyEvent("keyup",d));window.addEventListener("dblclick",d=>this._OnMouseEvent("dblclick",d,g));window.addEventListener("wheel",d=>
this._OnMouseWheelEvent("wheel",d));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",d=>{this._HandlePointerDownFocus(d);this._OnPointerEvent("pointerdown",d)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",d=>this._OnPointerRawUpdate(d))):
window.addEventListener("pointermove",d=>this._OnPointerEvent("pointermove",d)),window.addEventListener("pointerup",d=>this._OnPointerEvent("pointerup",d)),window.addEventListener("pointercancel",d=>this._OnPointerEvent("pointercancel",d))):(window.addEventListener("mousedown",d=>{this._HandlePointerDownFocus(d);this._OnMouseEventAsPointer("pointerdown",d)}),window.addEventListener("mousemove",d=>this._OnMouseEventAsPointer("pointermove",d)),window.addEventListener("mouseup",d=>this._OnMouseEventAsPointer("pointerup",
d)),window.addEventListener("touchstart",d=>{this._HandlePointerDownFocus(d);this._OnTouchEvent("pointerdown",d)}),window.addEventListener("touchmove",d=>this._OnTouchEvent("pointermove",d)),window.addEventListener("touchend",d=>this._OnTouchEvent("pointerup",d)),window.addEventListener("touchcancel",d=>this._OnTouchEvent("pointercancel",d)));const a=()=>this._PlayPendingMedia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);
window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}_PostRuntimeEvent(a,d){this.PostToRuntime(a,d||null,q)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_OnWindowResize(){const a=this._GetWindowInnerWidth(),d=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:a,innerHeight:d,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&
clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(a,d,0))}_ScheduleSimulatedResize(a,d,k){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(a,d,k),48)}_OnSimulatedResize(a,d,k){const l=this._GetWindowInnerWidth(),n=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;l!=a||n!=d?this._PostRuntimeEvent("window-resize",{innerWidth:l,innerHeight:n,devicePixelRatio:window.devicePixelRatio}):
10>k&&this._ScheduleSimulatedResize(l,n,k+1)}_OnSetTargetOrientation(a){this._targetOrientation=a.targetOrientation}_TrySetTargetOrientation(){const a=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(a):screen.webkitLockOrientation?d=screen.webkitLockOrientation(a):screen.mozLockOrientation?d=screen.mozLockOrientation(a):
screen.msLockOrientation&&(d=screen.msLockOrientation(a));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}_OnFullscreenChange(){const a=b.IsDocumentFullscreen();a&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:a,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(a){console.warn("[Construct 3] Fullscreen request failed: ",
a);this.PostToRuntime("fullscreenerror",{isFullscreen:b.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(a){a?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:a})}_OnKeyEvent(a,d){"Backspace"===d.key&&v(d);const k=e.get(d.code)||d.code;this._PostToRuntimeMaybeSync(a,{code:k,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,
metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},g)}_OnMouseWheelEvent(a,d){this.PostToRuntime(a,{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},g)}_OnMouseEvent(a,d,k){c(d)||this._PostToRuntimeMaybeSync(a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,timeStamp:d.timeStamp},k)}_OnMouseEventAsPointer(a,d){if(!c(d)){var k=this._mousePointerLastButtons;
"pointerdown"===a&&0!==k?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");this._PostToRuntimeMaybeSync(a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:k,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},g);this._mousePointerLastButtons=d.buttons;this._OnMouseEvent(d.type,d,m)}}_OnPointerEvent(a,d){this._pointerRawUpdateRateLimiter&&"pointermove"!==
a&&this._pointerRawUpdateRateLimiter.Reset();var k=0;"mouse"===d.pointerType&&(k=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:k,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},g);"mouse"===d.pointerType&&
(k="mousemove","pointerdown"===a?k="mousedown":"pointerup"===a&&(k="pointerup"),this._OnMouseEvent(k,d,m),this._mousePointerLastButtons=d.buttons)}_OnPointerRawUpdate(a){this._lastPointerRawUpdateEvent=a;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(a,d){for(let k=0,l=d.changedTouches.length;k<l;++k){const n=d.changedTouches[k];this._PostToRuntimeMaybeSync(a,
{pointerId:n.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:n.clientX,clientY:n.clientY,pageX:n.pageX,pageY:n.pageY,width:2*(n.radiusX||n.webkitRadiusX||0),height:2*(n.radiusY||n.webkitRadiusY||0),pressure:n.force||n.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:n.rotationAngle||0,timeStamp:d.timeStamp},g)}}_HandlePointerDownFocus(a){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(a.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",a=>this._OnDeviceOrientation(a)),window.addEventListener("deviceorientationabsolute",a=>this._OnDeviceOrientationAbsolute(a)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",a=>this._OnDeviceMotion(a)))}_OnDeviceOrientation(a){this.PostToRuntime("deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},g)}_OnDeviceOrientationAbsolute(a){this.PostToRuntime("deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},g)}_OnDeviceMotion(a){let d=
null;var k=a.acceleration;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;var l=a.accelerationIncludingGravity;l&&(k={x:l.x||0,y:l.y||0,z:l.z||0});l=null;const n=a.rotationRate;n&&(l={alpha:n.alpha||0,beta:n.beta||0,gamma:n.gamma||0});this.PostToRuntime("devicemotion",{acceleration:d,accelerationIncludingGravity:k,rotationRate:l,interval:a.interval,timeStamp:a.timeStamp},g)}_OnUpdateCanvasSize(a){const d=this.GetRuntimeInterface(),k=d.GetCanvas();k.style.width=a.styleWidth+"px";k.style.height=a.styleHeight+
"px";k.style.marginLeft=a.marginLeft+"px";k.style.marginTop=a.marginTop+"px";d.MaybeForceBodySize();this._isFirstSizeUpdate&&(k.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(a){const d=a.url;a=a.filename;const k=document.createElement("a"),l=document.body;k.textContent=a;k.href=d;k.download=a;l.appendChild(k);k.click();l.removeChild(k)}async _OnRasterSvgImage(a){var d=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);
d=d?await createImageBitmap(a,d):await createImageBitmap(a);return{imageBitmap:d,transferables:[d]}}async _OnGetSvgImageSize(a){return await self.C3_GetSvgImageSize(a.blob)}async _OnAddStylesheet(a){await p(a.url)}_PlayPendingMedia(){var a=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const d of a)(a=d.play())&&a.catch(k=>{this._mediaRemovedPendingPlay.has(d)||this._mediaPendingPlay.add(d)})}TryPlayMedia(a){if("function"!==typeof a.play)throw Error("missing play function");
this._mediaRemovedPendingPlay.delete(a);let d;try{d=a.play()}catch(k){this._mediaPendingPlay.add(a);return}d&&d.catch(k=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}RemovePendingPlay(a){this._mediaPendingPlay.delete(a);this._mediaRemovedPendingPlay.add(a)}SetSilent(a){this._isSilent=!!a}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(a){if(a.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var d=this._debugHighlightElem;d.style.display="";d.style.left=a.left-1+"px";d.style.top=a.top-1+"px";d.style.width=a.width+2+"px";d.style.height=a.height+2+"px";d.textContent=a.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}_InvokeFunctionFromJS(a,d){return this.PostToRuntimeAsync("js-invoke-function",{name:a,params:d})}_OnAlert(a){alert(a.message)}})}"use strict";
{const b=document.currentScript.src;self.JobSchedulerDOM=class{constructor(c){this._runtimeInterface=c;this._baseUrl=b?b.substr(0,b.lastIndexOf("/")+1):c.GetBaseURL();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var c=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=await this._runtimeInterface.CreateWorker(c,
this._baseUrl,{name:"DispatchWorker"});c=new MessageChannel;this._inputPort=c.port1;this._dispatchWorker.postMessage({type:"_init","in-port":c.port2},[c.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const c=this._jobWorkers.length;var e=this._runtimeInterface._GetWorkerURL("jobworker.js");e=await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"JobWorker"+c});const g=new MessageChannel,m=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:g.port1},[g.port1]);e.postMessage({type:"init",number:c,"dispatch-port":g.port2,"output-port":m.port2},[g.port2,m.port2]);this._jobWorkers.push(e);return m.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:"undefined"!==typeof OffscreenCanvas,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"user-media");this.SetAutoAttach(!1);this._isRuntimeInWorker=this._iRuntime.UsesWorker();this._sequenceNumber=0;this._lastActiveStream=null;this.AddRuntimeMessageHandler("get-media-sources",()=>this._OnGetMediaSources());this.AddDOMElementMessageHandler("request-camera",(c,e)=>this._OnRequestCamera(c,e));this.AddDOMElementMessageHandler("request-microphone",(c,e)=>this._OnRequestMicrophone(c,e));this.AddDOMElementMessageHandler("snapshot",
(c,e)=>this._Snapshot(c,e));this.AddDOMElementMessageHandler("stop",c=>this._Stop(c));self.C3UserMedia_GetVideoElement=c=>this.GetElementById(c);self.C3UserMedia_GetLastMediaStream=()=>this._lastActiveStream}CreateElement(b,c){const e=document.createElement("video");e.crossOrigin="anonymous";e.autoplay=!0;e.muted=!0;e.playsInline=!0;e.addEventListener("canplaythrough",()=>{this.PostToRuntimeElement("video-ready",b,{width:e.videoWidth,height:e.videoHeight})});return e}UpdateState(b,c){}DestroyElement(b){b.srcObject&&
(this._StopStream(b.srcObject),b.srcObject=null)}_StopStream(b){this._lastActiveStream===b&&(this._lastActiveStream=null);b=b.getTracks();for(let c=0,e=b.length;c<e;++c)b[c].stop()}async _OnGetMediaSources(){const b=[],c=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var e=await navigator.mediaDevices.enumerateDevices();for(const g of e){e=g.kind;const m={deviceId:g.deviceId,label:g.label,facing:g.facing||g.facingMode||""};"video"===e||"videoinput"===e?b.push(m):("audio"===
e||"audioinput"===e)&&c.push(m)}}return{videoSources:b,audioSources:c}}async _OnRequestCamera(b,c){try{const e="object"===typeof c.constraints.audio,g=this.GetRuntimeInterface();e?await g.RequirePermissions("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await g.RequirePermissions("CAMERA");this._lastActiveStream=await navigator.mediaDevices.getUserMedia(c.constraints);b.srcObject=this._lastActiveStream;b.play();this._isRuntimeInWorker&&this._StartTicking();return{ok:!0}}catch(e){return console.warn("Error requesting camera: ",
e),{ok:!1}}}async _OnRequestMicrophone(b,c){try{return await this.GetRuntimeInterface().RequirePermissions("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),this._lastActiveStream=await navigator.mediaDevices.getUserMedia(c.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(this._lastActiveStream,c.tag),{ok:!0}}catch(e){return console.warn("Error requesting microphone: ",e),{ok:!1}}}_CanvasToURL(b,c,e){return new Promise((g,m)=>{b.toBlob?b.toBlob(q=>g(URL.createObjectURL(q)),c,e):
g(b.toDataURL(c,e))})}async _Snapshot(b,c){const e=document.createElement("canvas");e.width=b.videoWidth;e.height=b.videoHeight;e.getContext("2d").drawImage(b,0,0,b.videoWidth,b.videoHeight);return{snapshotUrl:await this._CanvasToURL(e,c.format,c.quality)}}_Stop(b){b.srcObject&&(this._StopStream(b.srcObject),b.srcObject=null)}Tick(){if(this._isRuntimeInWorker){var b={},c={sequenceNumber:this._sequenceNumber++,videoData:b},e=[],g=[];for(const [m,q]of this._elementMap.entries()){if(!q.srcObject)continue;
const p={};g.push(createImageBitmap(q).then(u=>{p.imageBitmap=u;e.push(u)}).catch(u=>{p.imageBitmap=null}));b[m.toString()]=p}Promise.all(g).then(()=>this.PostToRuntime("state",c,!1,e))}}});"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"button")}CreateElement(c,e){const g=document.createElement("input");var m=g;e.isCheckbox?(g.type="checkbox",m=document.createElement("label"),m.appendChild(g),m.appendChild(document.createTextNode("")),m.style.fontFamily="sans-serif",m.style.userSelect="none",m.style.webkitUserSelect="none",m.style.display="inline-block",m.style.color="black"):g.type="button";m.style.position=
"absolute";m.addEventListener("touchstart",b);m.addEventListener("touchmove",b);m.addEventListener("touchend",b);m.addEventListener("mousedown",b);m.addEventListener("mouseup",b);m.addEventListener("keydown",b);m.addEventListener("keyup",b);g.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",c,{isChecked:g.checked}));e.id&&(g.id=e.id);this.UpdateState(m,e);return m}_GetInputElem(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}_GetFocusElement(c){return this._GetInputElem(c)}UpdateState(c,
e){const g=this._GetInputElem(c);g.checked=e.isChecked;g.disabled=!e.isEnabled;c.title=e.title;c===g?g.value=e.text:c.lastChild.textContent=e.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",c=>this._OnGetInitialState(c)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",c=>this._OnAlert(c)],["close",()=>this._OnClose()],["set-focus",c=>this._OnSetFocus(c)],["vibrate",c=>this._OnVibrate(c)],["lock-orientation",c=>this._OnLockOrientation(c)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",c=>this._OnNavigate(c)],["request-fullscreen",c=>this._OnRequestFullscreen(c)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",c=>this._OnSetHash(c)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
c=>this._OnWin10BackRequested(c))}_OnGetInitialState(b){this._exportType=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(b=>
this.PostToRuntime("sw-message",b.data))}_OnOnlineStateChanged(b){this.PostToRuntime("online-state",{isOnline:b})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(b){b.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(b){alert(b.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(b){b=
b.isFocus;if("nwjs"===this._exportType){const c=this.GetNWjsWindow();b?c.focus():c.blur()}else b?window.focus():window.blur()}_OnVibrate(b){navigator.vibrate&&navigator.vibrate(b.pattern)}_OnLockOrientation(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):
screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(b){}}_OnNavigate(b){var c=b.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===c)window.forward();else if("home"===c)window.home();else if("reload"===c)location.reload();else if("url"===c){c=b.url;var e=b.target;b=b.exportType;"windows-uwp"===b&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(c,"_system"):"preview"===b?window.open(c,"_blank"):this._isScirraArcade||(2===e?window.top.location=c:1===e?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=b.url,e=b.tag,"windows-uwp"===b.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,e))}_OnRequestFullscreen(b){const c={navigationUI:"auto"};
b=b.navUI;1===b?c.navigationUI="hide":2===b&&(c.navigationUI="show");b=document.documentElement;b.requestFullscreen?b.requestFullscreen(c):b.mozRequestFullScreen?b.mozRequestFullScreen(c):b.msRequestFullscreen?b.msRequestFullscreen(c):b.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?b.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):b.webkitRequestFullScreen())}_OnExitFullscreen(){document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}_OnSetHash(b){location.hash=b.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"list");this.AddDOMElementMessageHandler("set-selected-index",(e,g)=>this._OnSetSelectedIndex(e,g.selectedIndex));this.AddDOMElementMessageHandler("add-item",(e,g)=>this._OnAddItem(e,g));this.AddDOMElementMessageHandler("remove-item",(e,g)=>this._OnRemoveItem(e,g));this.AddDOMElementMessageHandler("set-item",(e,g)=>this._OnSetItem(e,g));this.AddDOMElementMessageHandler("clear",
e=>this._OnClear(e));this.AddDOMElementMessageHandler("load-state",(e,g)=>this._OnLoadState(e,g))}CreateElement(c,e){const g=e.isDropdown,m=e.isMultiSelect,q=e.items,p=document.createElement("select");p.style.position="absolute";p.style.userSelect="none";p.style.webkitUserSelect="none";p.multiple=m;g||(p.size=2);for(const u of q)p.add(this._CreateOption(u));p.addEventListener("touchstart",b);p.addEventListener("touchmove",b);p.addEventListener("touchend",b);p.addEventListener("mousedown",b);p.addEventListener("mouseup",
b);p.addEventListener("click",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("click",c,this._GetSelectionState(p))});p.addEventListener("dblclick",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",c,this._GetSelectionState(p))});p.addEventListener("change",()=>this.PostToRuntimeElement("change",c,this._GetSelectionState(p)));e.id&&(p.id=e.id);this.UpdateState(p,e);return p}_CreateOption(c){const e=document.createElement("option");e.text=c;return e}_GetSelectionState(c){const e=
c.selectedIndex,g=[];for(let m=0,q=c.length;m<q;++m)c.options[m].selected&&g.push(m);return{selectedIndex:e,selectedIndices:g}}UpdateState(c,e){c.title=e.title;c.disabled=!e.isEnabled;c.multiple=!!e.isMultiSelect}_OnSetSelectedIndex(c,e){c.selectedIndex=e}_OnAddItem(c,e){const g=e.index;e=this._CreateOption(e.text);0>g?c.add(e):c.add(e,g)}_OnRemoveItem(c,e){c.remove(e.index)}_OnSetItem(c,e){c.options[e.index].text=e.text}_OnClear(c){c.innerHTML=""}_OnLoadState(c,e){c.innerHTML="";for(const g of e.items)c.add(this._CreateOption(g));
c.selectedIndex=e.selectedIndex;for(const g of e.selectedIndices)if(e=c.options[g])e.selected=!0}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"game-recorder");this._mediaStream=this._mediaRecorder=null;this._stopStreamOnEnd=!0;this._recordedChunks=[];this._lastRecordingUrl="";this.AddRuntimeMessageHandler("get-supported-formats",()=>this._OnGetSupportedFormats());this.AddRuntimeMessageHandler("start-recording",c=>this._OnStartRecording(c));this.AddRuntimeMessageHandler("start-screen-recording",c=>this._OnStartScreenRecording(c));this.AddRuntimeMessageHandler("start-user-media-recording",
c=>this._OnStartUserMediaRecording(c));this.AddRuntimeMessageHandler("stop-recording",()=>this._OnStopRecording());this._MaybePolyfillGetDisplayMedia()}_MaybePolyfillGetDisplayMedia(){navigator.mediaDevices&&navigator.mediaDevices.getDisplayMedia||navigator.mediaDevices&&navigator.mediaDevices.getSupportedConstraints&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getSupportedConstraints().mediaSource&&(navigator.mediaDevices.getDisplayMedia=function(){return navigator.mediaDevices.getUserMedia({video:{mediaSource:"screen"}})})}_OnGetSupportedFormats(){var b=
this._iRuntime.GetCanvas();const c="undefined"!==typeof MediaRecorder;b=!(!b.captureStream||!c);const e=[],g=[];b&&(MediaRecorder.isTypeSupported("video/webm;codecs=vp8")&&e.push("video/webm;codecs=vp8"),MediaRecorder.isTypeSupported("video/webm;codecs=vp9")&&e.push("video/webm;codecs=vp9"),MediaRecorder.isTypeSupported("audio/ogg;codecs=opus")&&g.push("audio/ogg;codecs=opus"),MediaRecorder.isTypeSupported("audio/webm;codecs=opus")&&g.push("audio/webm;codecs=opus"));return{isSupported:b,isMediaRecorderSupported:c,
isScreenRecordingSupported:!(!navigator.mediaDevices||!navigator.mediaDevices.getDisplayMedia||"undefined"===typeof MediaRecorder),supportedVideoFormats:e,supportedAudioFormats:g}}_StopStreamVideoTracks(b){b=b.getTracks();for(let c=0,e=b.length;c<e;++c){const g=b[c];"video"===g.kind&&g.stop()}}_StopAnyPriorRecording(){this._OnStopRecording();this._recordedChunks.length=0;this._lastRecordingUrl&&(URL.revokeObjectURL(this._lastRecordingUrl),this._lastRecordingUrl="")}_OnStartRecording(b){const c=b.videoType,
e=b.audioType,g=b.bitsPerSecond;b=b.framerate;this._StopAnyPriorRecording();let m=[],q=[];try{if(c){const p=this._iRuntime.GetCanvas();m=(0<b?p.captureStream(b):p.captureStream()).getVideoTracks()}e&&self.C3Audio_GetOutputStream&&(q=self.C3Audio_GetOutputStream().getAudioTracks());this._mediaStream=new MediaStream([...m,...q]);this._stopStreamOnEnd=!0;this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:c||e,bitsPerSecond:g})}catch(p){console.error("[Game Recorder] Failed to start recording: ",
p),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}async _OnStartScreenRecording(b){const c=b.videoType,e=b.audioType;b=b.bitsPerSecond;this._StopAnyPriorRecording();let g=[],m=[];try{c&&(g=(await navigator.mediaDevices.getDisplayMedia({video:!0})).getVideoTracks()),e&&self.C3Audio_GetOutputStream&&(m=self.C3Audio_GetOutputStream().getAudioTracks()),this._mediaStream=new MediaStream([...g,...m]),this._stopStreamOnEnd=!0,this._mediaStream.addEventListener("inactive",()=>this._OnMediaStreamInactive()),
this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:c||e,bitsPerSecond:b})}catch(q){console.error("[Game Recorder] Failed to start recording: ",q),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}async _OnStartUserMediaRecording(b){const c=b.videoType,e=b.audioType;b=b.bitsPerSecond;this._StopAnyPriorRecording();if(self.C3UserMedia_GetLastMediaStream){var g=self.C3UserMedia_GetLastMediaStream();if(g){try{this._mediaStream=g,this._stopStreamOnEnd=!1,this._mediaRecorder=new MediaRecorder(this._mediaStream,
{mimeType:c||e,bitsPerSecond:b})}catch(m){console.error("[Game Recorder] Failed to start recording: ",m),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}}}_StartMediaRecorder(b,c){this._mediaRecorder.ondataavailable=e=>{this._recordedChunks.push(e.data)};this._mediaRecorder.onerror=e=>{console.error("[Game Recorder] Error recording: ",e);this.PostToRuntime("error")};this._mediaRecorder.onwarning=e=>{console.warn("[Game Recorder] Recording warning: ",e)};this._mediaRecorder.onstop=e=>{e=
new Blob(this._recordedChunks,{type:b||c});this._lastRecordingUrl=URL.createObjectURL(e);this.PostToRuntime("recording-ready",{url:this._lastRecordingUrl})};this._mediaRecorder.start()}_OnMediaStreamInactive(){this.PostToRuntime("screen-recording-stopped");this._OnStopRecording()}_OnStopRecording(){this._mediaRecorder&&(this._mediaRecorder.stop(),this._mediaRecorder=null);this._mediaStream&&(this._stopStreamOnEnd&&this._StopStreamVideoTracks(this._mediaStream),this._mediaStream=null)}});"use strict";
{function b(e){e.stopPropagation()}function c(e){13!==e.which&&27!==e.which&&e.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(e){super(e,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",g=>this._OnScrollToBottom(g))}CreateElement(e,g){let m;const q=g.type;"textarea"===q?(m=document.createElement("textarea"),m.style.resize="none"):(m=document.createElement("input"),m.type=q);m.style.position="absolute";m.autocomplete="off";
m.addEventListener("touchstart",b);m.addEventListener("touchmove",b);m.addEventListener("touchend",b);m.addEventListener("mousedown",b);m.addEventListener("mouseup",b);m.addEventListener("keydown",c);m.addEventListener("keyup",c);m.addEventListener("click",p=>{p.stopPropagation();this._PostToRuntimeElementMaybeSync("click",e)});m.addEventListener("dblclick",p=>{p.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",e)});m.addEventListener("input",()=>this.PostToRuntimeElement("change",
e,{text:m.value}));g.id&&(m.id=g.id);this.UpdateState(m,g);return m}UpdateState(e,g){e.value=g.text;e.placeholder=g.placeholder;e.title=g.title;e.disabled=!g.isEnabled;e.readOnly=g.isReadOnly;e.spellcheck=g.spellCheck;g=g.maxLength;0>g?e.removeAttribute("maxlength"):e.setAttribute("maxlength",g)}_OnScrollToBottom(e){e.scrollTop=e.scrollHeight}})}"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"sliderbar")}CreateElement(c,e){const g=document.createElement("input");g.type="range";g.style.position="absolute";g.style.userSelect="none";g.style.webkitUserSelect="none";g.addEventListener("touchstart",b);g.addEventListener("touchmove",b);g.addEventListener("touchend",b);g.addEventListener("mousedown",b);g.addEventListener("mouseup",b);g.addEventListener("keydown",
b);g.addEventListener("keyup",b);g.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",c));g.addEventListener("change",()=>this.PostToRuntimeElement("change",c,{value:parseFloat(g.value)}));g.addEventListener("input",()=>this.PostToRuntimeElement("input",c,{value:parseFloat(g.value)}));e.id&&(g.id=e.id);this.UpdateState(g,e);return g}UpdateState(c,e){c.max=e.max;c.min=e.min;c.step=e.step;c.value=e.value;c.disabled=!e.isEnabled;c.title=e.title}})};