'use strict';window.DOMHandler=class{constructor(b,c){this._iRuntime=b;this._componentId=c;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(b,c,e,h){this._iRuntime.PostToRuntimeComponent(this._componentId,b,c,e,h)}PostToRuntimeAsync(b,c,e,h){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,b,c,e,h)}_PostToRuntimeMaybeSync(b,c,e){this._iRuntime.UsesWorker()?this.PostToRuntime(b,c,e):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:b,dispatchOpts:e||null,data:c,responseId:null})}AddRuntimeMessageHandler(b,c){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,b,c)}AddRuntimeMessageHandlers(b){for(const [c,e]of b)this.AddRuntimeMessageHandler(c,e)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(b,c){this._callback=b;this._interval=c;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(b){this._canRunImmediate=!!b}Call(){if(-1===this._timerId){var b=Date.now(),c=b-this._lastCallTime,e=this._interval;c>=e&&this._canRunImmediate?(this._lastCallTime=b,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(e-c,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(b,c){super(b,c);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",e=>this._OnCreate(e)],["destroy",e=>this._OnDestroy(e)],["set-visible",e=>this._OnSetVisible(e)],["update-position",e=>this._OnUpdatePosition(e)],["update-state",e=>this._OnUpdateState(e)],["focus",e=>this._OnSetFocus(e)],["set-css-style",e=>this._OnSetCssStyle(e)],["set-attribute",e=>this._OnSetAttribute(e)],["remove-attribute",
e=>this._OnRemoveAttribute(e)]]);this.AddDOMElementMessageHandler("get-element",e=>e)}SetAutoAttach(b){this._autoAttach=!!b}AddDOMElementMessageHandler(b,c){this.AddRuntimeMessageHandler(b,e=>{const h=this._elementMap.get(e.elementId);return c(h,e)})}_OnCreate(b){const c=b.elementId,e=this.CreateElement(c,b);this._elementMap.set(c,e);b.isVisible||(e.style.display="none");b=this._GetFocusElement(e);b.addEventListener("focus",h=>this._OnFocus(c));b.addEventListener("blur",h=>this._OnBlur(c));this._autoAttach&&
document.body.appendChild(e)}CreateElement(b,c){throw Error("required override");}DestroyElement(b){}_OnDestroy(b){b=b.elementId;const c=this._elementMap.get(b);this.DestroyElement(c);this._autoAttach&&c.parentElement.removeChild(c);this._elementMap.delete(b)}PostToRuntimeElement(b,c,e){e||(e={});e.elementId=c;this.PostToRuntime(b,e)}_PostToRuntimeElementMaybeSync(b,c,e){e||(e={});e.elementId=c;this._PostToRuntimeMaybeSync(b,e)}_OnSetVisible(b){this._autoAttach&&(this._elementMap.get(b.elementId).style.display=
b.isVisible?"":"none")}_OnUpdatePosition(b){if(this._autoAttach){var c=this._elementMap.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}_OnUpdateState(b){const c=this._elementMap.get(b.elementId);this.UpdateState(c,b)}UpdateState(b,c){throw Error("required override");}_GetFocusElement(b){return b}_OnFocus(b){this.PostToRuntimeElement("elem-focused",b)}_OnBlur(b){this.PostToRuntimeElement("elem-blurred",
b)}_OnSetFocus(b){const c=this._GetFocusElement(this._elementMap.get(b.elementId));b.focus?c.focus():c.blur()}_OnSetCssStyle(b){this._elementMap.get(b.elementId).style[b.prop]=b.val}_OnSetAttribute(b){this._elementMap.get(b.elementId).setAttribute(b.name,b.val)}_OnRemoveAttribute(b){this._elementMap.get(b.elementId).removeAttribute(b.name)}GetElementById(b){return this._elementMap.get(b)}};"use strict";
{const b=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function c(d,a){const f=document.createElement("script");f.async=!1;"module"===a&&(f.type="module");if(d.isStringSrc)f.textContent=d.str,document.head.appendChild(f);else return new Promise((g,k)=>{f.onload=g;f.onerror=k;f.src=d;document.head.appendChild(f)})}let e=!1,h=!1;function l(){if(!e){try{new Worker("blob://",{get type(){h=!0}})}catch(d){}e=!0}return h}let p=new Audio;const n={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),
"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function t(d){d=await w(d);return(new TextDecoder("utf-8")).decode(d)}function w(d){return new Promise((a,f)=>{const g=new FileReader;g.onload=k=>a(k.target.result);g.onerror=k=>f(k);g.readAsArrayBuffer(d)})}
const A=[];let y=0;window.RealFile=window.File;const x=[],B=new Map,u=new Map;let C=0;const z=[];self.runOnStartup=function(d){if("function"!==typeof d)throw Error("runOnStartup called without a function");z.push(d)};const E=new Set(["cordova","playable-ad","instant-games"]);function D(d){return E.has(d)}window.RuntimeInterface=class d{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._scriptsType=a.scriptsType;this._workerScriptURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this._scriptsType||l())||(this._useWorker=!1);D(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",f=>this._OnCordovaFetchLocalFile(f));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",
f=>this._OnCreateJobWorker(f));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return b&&
"cordova"===this._exportType}IsiOSWebView(){return b&&D(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let g=0,k=a.engineScripts.length;g<k;++g){var f=a.engineScripts[g].toLowerCase();this._localFileStrings.hasOwnProperty(f)?a.engineScripts[g]={isStringSrc:!0,str:this._localFileStrings[f]}:this._localFileBlobs.hasOwnProperty(f)&&(a.engineScripts[g]=
URL.createObjectURL(this._localFileBlobs[f]))}}a.baseUrl?this._baseUrl=a.baseUrl:(f=location.origin,this._baseUrl=("null"===f?"file:///":f)+location.pathname,f=this._baseUrl.lastIndexOf("/"),-1!==f&&(this._baseUrl=this._baseUrl.substr(0,f+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);f=new MessageChannel;this._messageChannelPort=f.port1;this._messageChannelPort.onmessage=g=>this._OnMessageFromRuntime(g.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(g=>this._OnMessageFromDebugger(g));
this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,f.port2):await this._InitDOM(a,f.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,f,g){if(a.startsWith("blob:"))return new Worker(a,g);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),
g);a=new URL(a,f);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),g)}return new Worker(a,g)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}MaybeForceBodySize(){if(this.IsiOSWebView()){const a=document.documentElement.style,f=document.body.style,g=Math.floor(1.5*Math.max(window.screen.width,window.screen.height));
a.width=g+"px";a.height=g+"px";f.width=g+"px";f.height=g+"px"}}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:d.IsDocumentFullscreen(),projectData:a.projectData,scriptsType:a.scriptsType,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:n,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,
f){var g=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(g,this._baseUrl,{type:this._scriptsType,name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";g=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:f,canvas:g,workerDependencyScripts:a.workerDependencyScripts||
[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[f,g,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=x.map(k=>new k(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(k,m)=>this._runtimeDomHandler._InvokeFunctionFromJS(k,m);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,f){this._canvas=
document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=x.map(m=>new m(this));this._FindRuntimeDOMHandler();var g=a.engineScripts.map(m=>"string"===typeof m?(new URL(m,this._baseUrl)).toString():m);Array.isArray(a.workerDependencyScripts)&&g.unshift(...a.workerDependencyScripts);g=await Promise.all(g.map(m=>this._MaybeGetCordovaScriptURL(m,this._scriptsType)));await Promise.all(g.map(m=>c(m,this._scriptsType)));
const k=self.C3_ProjectScriptsStatus;if("module"===this._scriptsType){g=a.mainProjectScript;const m=a.projectScripts;for(let [r,q]of m)if(q||(q=r),r===g)try{q=await this._MaybeGetCordovaScriptURL(q,this._scriptsType),await c(q,this._scriptsType),"preview"!==this._exportType||k[r]||this._ReportProjectMainScriptError(r,"main script did not run to completion")}catch(v){this._ReportProjectMainScriptError(r,v)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))q=await this._MaybeGetCordovaScriptURL(q,
this._scriptsType),await c(q,this._scriptsType)}else if(a.projectScripts&&0<a.projectScripts.length)try{if(await Promise.all(a.projectScripts.map(m=>c(m[1],this._scriptsType))),Object.values(k).some(m=>!m)){self.setTimeout(()=>this._ReportProjectScriptError(k),100);return}}catch(m){console.error("[Preview] Error loading project scripts: ",m);self.setTimeout(()=>this._ReportProjectScriptError(k),100);return}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),
console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:f,canvas:this._canvas,runOnStartupFunctions:z}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){this._RemoveLoadingMessage();
a=`Failed to load project script '${Object.entries(a).filter(f=>!f[1]).map(f=>f[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}_ReportProjectMainScriptError(a,f){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,f);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,f,g,k,m){this._messageChannelPort.postMessage({type:"event",component:a,handler:f,dispatchOpts:k||null,data:g,responseId:null},m)}PostToRuntimeComponentAsync(a,
f,g,k,m){const r=C++,q=new Promise((v,F)=>{u.set(r,{resolve:v,reject:F})});this._messageChannelPort.postMessage({type:"event",component:a,handler:f,dispatchOpts:k||null,data:g,responseId:r},m);return q}["_OnMessageFromRuntime"](a){const f=a.type;if("event"===f)return this._OnEventFromRuntime(a);if("result"===f)this._OnResultFromRuntime(a);else if("runtime-ready"===f)this._OnRuntimeReady();else if("alert-error"===f)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===f)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${f}'`);}_OnEventFromRuntime(a){const f=a.component,g=a.handler,k=a.data,m=a.responseId;if(a=B.get(f))if(a=a.get(g)){var r=null;try{r=a(k)}catch(q){console.error(`Exception in '${f}' handler '${g}':`,q);null!==m&&this._PostResultToRuntime(m,!1,""+q);return}if(null===m)return r;r&&r.then?r.then(q=>this._PostResultToRuntime(m,!0,q)).catch(q=>{console.error(`Rejection from '${f}' handler '${g}':`,q);this._PostResultToRuntime(m,!1,""+q)}):this._PostResultToRuntime(m,
!0,r)}else console.warn(`[DOM] No handler '${g}' for component '${f}'`);else console.warn(`[DOM] No event handlers for component '${f}'`)}_PostResultToRuntime(a,f,g){let k;g&&g.transferables&&(k=g.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:f,result:g},k)}_OnResultFromRuntime(a){const f=a.responseId,g=a.isOk;a=a.result;const k=u.get(f);g?k.resolve(a):k.reject(a);u.delete(f)}AddRuntimeComponentMessageHandler(a,f,g){let k=B.get(a);k||(k=new Map,B.set(a,k));if(k.has(f))throw Error(`[DOM] Component '${a}' already has handler '${f}'`);
k.set(f,g)}static AddDOMHandlerClass(a){if(x.includes(a))throw Error("DOM handler already added");x.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==
this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!n[a]}async _WasmDecodeWebMOpus(a){a=await this.PostToRuntimeComponentAsync("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a,f){return"cordova"===this._exportType&&"module"===f&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],
{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const f=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(f);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(f);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,f){a=
a[f];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const f=this._GetPermissionAPI();return new Promise((g,k)=>f.checkPermission(this._MapPermissionID(f,a),m=>g(!!m.hasPermission),k))}_RequestPermission(a){const f=this._GetPermissionAPI();return new Promise((g,k)=>f.requestPermission(this._MapPermissionID(f,a),m=>g(!!m.hasPermission),k))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const f of a)if(!await this._HasPermission(f)&&
!1===await this._RequestPermission(f))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const f=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((g,k)=>{window.resolveLocalFileSystemURL(f,m=>{m.file(g,k)},k)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await t(a)}_CordovaMaybeStartNextArrayBufferRead(){if(A.length&&!(8<=y)){y++;
var a=A.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((f,g)=>{A.push({filename:a,successCallback:k=>{y--;this._CordovaMaybeStartNextArrayBufferRead();f(k)},errorCallback:k=>{y--;this._CordovaMaybeStartNextArrayBufferRead();g(k)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,f,g){try{const k=await this.CordovaFetchLocalFile(a),m=await w(k);
f(m)}catch(k){g(k)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [f,g]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(f,g));await Promise.all(a)}async _ConvertDataUriToBlobs(a,f){if("object"===typeof f)this._localFileBlobs[a]=new Blob([f.str],{type:f.type}),this._localFileStrings[a]=f.str;else{let g=await this._FetchDataUri(f);g||(g=this._DataURIToBinaryBlobSync(f));this._localFileBlobs[a]=g}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(f){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
f),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var f=a.indexOf(",");if(0>f)throw new URIError("expected comma in data: uri");var g=a.substring(5,f);a=a.substring(f+1);f=g.split(";");g=f[0]||"";const k=f[2];a="base64"===f[1]||"base64"===k?atob(a):decodeURIComponent(a);return{mime_type:g,data:a}}_BinaryStringToBlob(a,f){var g=a.length;let k=g>>2,m=new Uint8Array(g),r=new Uint32Array(m.buffer,0,k),q,v;for(v=q=0;q<k;++q)r[q]=
a.charCodeAt(v++)|a.charCodeAt(v++)<<8|a.charCodeAt(v++)<<16|a.charCodeAt(v++)<<24;for(g&=3;g--;)m[v]=a.charCodeAt(v),++v;return new Blob([m],{type:f})}}}"use strict";
{const b=self.RuntimeInterface;function c(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents}const e=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},p={dispatchRuntimeEvent:!0};function n(d){return new Promise((a,f)=>{const g=document.createElement("link");g.onload=()=>a(g);g.onerror=
k=>f(k);g.rel="stylesheet";g.href=d;document.head.appendChild(g)})}function t(d){return new Promise((a,f)=>{const g=new Image;g.onload=()=>a(g);g.onerror=k=>f(k);g.src=d})}async function w(d){d=URL.createObjectURL(d);try{return await t(d)}finally{URL.revokeObjectURL(d)}}function A(d){return new Promise((a,f)=>{let g=new FileReader;g.onload=k=>a(k.target.result);g.onerror=k=>f(k);g.readAsText(d)})}async function y(d,a,f){if(!/firefox/i.test(navigator.userAgent))return await w(d);var g=await A(d);g=
(new DOMParser).parseFromString(g,"image/svg+xml");const k=g.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const m=k.getAttribute("width"),r=k.getAttribute("height");if(!m.includes("%")&&!r.includes("%"))return await w(d)}k.setAttribute("width",a+"px");k.setAttribute("height",f+"px");g=(new XMLSerializer).serializeToString(g);d=new Blob([g],{type:"image/svg+xml"});return await w(d)}function x(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;d=d.parentNode}while(d);
return!1}const B=new Set(["canvas","body","html"]);function u(d){const a=d.target.tagName.toLowerCase();B.has(a)&&d.preventDefault()}function C(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()}self.C3_GetSvgImageSize=async function(d){d=await w(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const a=d.getBoundingClientRect();document.body.removeChild(d);return[a.width,a.height]}};
self.C3_RasterSvgImageBlob=async function(d,a,f,g,k){d=await y(d,a,f);const m=document.createElement("canvas");m.width=g;m.height=k;m.getContext("2d").drawImage(d,0,0,a,f);return m};let z=!1;document.addEventListener("pause",()=>z=!0);document.addEventListener("resume",()=>z=!1);function E(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}}function D(){const d=document.activeElement;if(!d)return!1;const a=d.tagName.toLowerCase(),f=new Set("email number password search tel text url".split(" "));
return"textarea"===a?!0:"input"===a?f.has(d.type.toLowerCase()||"text"):x(d)}b.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;d.AddRuntimeComponentMessageHandler("canvas","update-size",g=>this._OnUpdateCanvasSize(g));
d.AddRuntimeComponentMessageHandler("runtime","invoke-download",g=>this._OnInvokeDownload(g));d.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",g=>this._OnRasterSvgImage(g));d.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",g=>this._OnGetSvgImageSize(g));d.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",g=>this._OnSetTargetOrientation(g));d.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());d.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",g=>this._OnPostToDebugger(g));d.AddRuntimeComponentMessageHandler("runtime","go-to-script",g=>this._OnPostToDebugger(g));d.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());d.AddRuntimeComponentMessageHandler("runtime","debug-highlight",g=>this._OnDebugHighlight(g));d.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());d.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());d.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",g=>this._OnAddStylesheet(g));d.AddRuntimeComponentMessageHandler("runtime","alert",g=>this._OnAlert(g));d.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const k=g.target,m=k.tagName.toLowerCase();a.has(m)||x(k)||g.preventDefault()});const f=d.GetCanvas();window.addEventListener("selectstart",
u);window.addEventListener("gesturehold",u);f.addEventListener("selectstart",u);f.addEventListener("gesturehold",u);window.addEventListener("touchstart",u,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),f.addEventListener("pointerdown",u)):f.addEventListener("touchstart",u);this._mousePointerLastButtons=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",C,{passive:!1});window.addEventListener("wheel",
C,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",g=>this._OnFullscreenError(g));window.addEventListener("webkitfullscreenerror",g=>this._OnFullscreenError(g));window.addEventListener("mozfullscreenerror",
g=>this._OnFullscreenError(g));d.IsiOSWebView()&&window.addEventListener("focusout",()=>{D()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));
return{isSuspended:!(!document.hidden&&!z)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:E()});this._mousePointerLastButtons=0});window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,h));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",
a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):window.addEventListener("pointermove",
a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",a)),window.addEventListener("touchstart",
a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const d=()=>this._PlayPendingMedia();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);
window.addEventListener("gamepadconnected",d,!0)}_PostRuntimeEvent(d,a){this.PostToRuntime(d,a||null,p)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const d=this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:a,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&
clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(d,a,0))}_ScheduleSimulatedResize(d,a,f){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(d,a,f),48)}_OnSimulatedResize(d,a,f){const g=this._GetWindowInnerWidth(),k=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;g!=d||k!=a?this._PostRuntimeEvent("window-resize",{innerWidth:g,innerHeight:k,devicePixelRatio:window.devicePixelRatio}):
10>f&&this._ScheduleSimulatedResize(g,k,f+1)}_OnSetTargetOrientation(d){this._targetOrientation=d.targetOrientation}_TrySetTargetOrientation(){const d=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(d):screen.webkitLockOrientation?a=screen.webkitLockOrientation(d):screen.mozLockOrientation?a=screen.mozLockOrientation(d):
screen.msLockOrientation&&(a=screen.msLockOrientation(d));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}_OnFullscreenChange(){const d=b.IsDocumentFullscreen();d&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:d,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(d){console.warn("[Construct 3] Fullscreen request failed: ",
d);this.PostToRuntime("fullscreenerror",{isFullscreen:b.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(d){d?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:d})}_OnKeyEvent(d,a){"Backspace"===a.key&&u(a);const f=e.get(a.code)||a.code;this._PostToRuntimeMaybeSync(d,{code:f,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,
metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},h)}_OnMouseWheelEvent(d,a){this.PostToRuntime(d,{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},h)}_OnMouseEvent(d,a,f){c(a)||this._PostToRuntimeMaybeSync(d,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},f)}_OnMouseEventAsPointer(d,a){if(!c(a)){var f=this._mousePointerLastButtons;
"pointerdown"===d&&0!==f?d="pointermove":"pointerup"===d&&0!==a.buttons&&(d="pointermove");this._PostToRuntimeMaybeSync(d,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:f,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},h);this._mousePointerLastButtons=a.buttons;this._OnMouseEvent(a.type,a,l)}}_OnPointerEvent(d,a){this._pointerRawUpdateRateLimiter&&"pointermove"!==
d&&this._pointerRawUpdateRateLimiter.Reset();var f=0;"mouse"===a.pointerType&&(f=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(d,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,lastButtons:f,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},h);"mouse"===a.pointerType&&
(f="mousemove","pointerdown"===d?f="mousedown":"pointerup"===d&&(f="mouseup"),this._OnMouseEvent(f,a,l),this._mousePointerLastButtons=a.buttons)}_OnPointerRawUpdate(d){this._lastPointerRawUpdateEvent=d;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(d,a){for(let f=0,g=a.changedTouches.length;f<g;++f){const k=a.changedTouches[f];this._PostToRuntimeMaybeSync(d,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:a.timeStamp},h)}}_HandlePointerDownFocus(d){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(d.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",d=>this._OnDeviceOrientation(d)),window.addEventListener("deviceorientationabsolute",d=>this._OnDeviceOrientationAbsolute(d)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",d=>this._OnDeviceMotion(d)))}_OnDeviceOrientation(d){this.PostToRuntime("deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},h)}_OnDeviceOrientationAbsolute(d){this.PostToRuntime("deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},h)}_OnDeviceMotion(d){let a=
null;var f=d.acceleration;f&&(a={x:f.x||0,y:f.y||0,z:f.z||0});f=null;var g=d.accelerationIncludingGravity;g&&(f={x:g.x||0,y:g.y||0,z:g.z||0});g=null;const k=d.rotationRate;k&&(g={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:f,rotationRate:g,interval:d.interval,timeStamp:d.timeStamp},h)}_OnUpdateCanvasSize(d){const a=this.GetRuntimeInterface(),f=a.GetCanvas();f.style.width=d.styleWidth+"px";f.style.height=d.styleHeight+
"px";f.style.marginLeft=d.marginLeft+"px";f.style.marginTop=d.marginTop+"px";a.MaybeForceBodySize();this._isFirstSizeUpdate&&(f.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(d){const a=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=a;f.download=d;g.appendChild(f);f.click();g.removeChild(f)}async _OnRasterSvgImage(d){var a=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);
a=a?await createImageBitmap(d,a):await createImageBitmap(d);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(d){return await self.C3_GetSvgImageSize(d.blob)}async _OnAddStylesheet(d){await n(d.url)}_PlayPendingMedia(){var d=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of d)(d=a.play())&&d.catch(f=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(d){if("function"!==typeof d.play)throw Error("missing play function");
this._mediaRemovedPendingPlay.delete(d);let a;try{a=d.play()}catch(f){this._mediaPendingPlay.add(d);return}a&&a.catch(f=>{this._mediaRemovedPendingPlay.has(d)||this._mediaPendingPlay.add(d)})}RemovePendingPlay(d){this._mediaPendingPlay.delete(d);this._mediaRemovedPendingPlay.add(d)}SetSilent(d){this._isSilent=!!d}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(d){if(d.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=d.left-1+"px";a.style.top=d.top-1+"px";a.style.width=d.width+2+"px";a.style.height=d.height+2+"px";a.textContent=d.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(d){window.c3_postToMessagePort&&
(d.from="runtime",window.c3_postToMessagePort(d))}_InvokeFunctionFromJS(d,a){return this.PostToRuntimeAsync("js-invoke-function",{name:d,params:a})}_OnAlert(d){alert(d.message)}})}"use strict";
self.JobSchedulerDOM=class{constructor(b){this._runtimeInterface=b;this._baseUrl=b.GetBaseURL();"preview"===b.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=b.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var b=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(b,this._baseUrl,{name:"DispatchWorker"});b=new MessageChannel;this._inputPort=b.port1;this._dispatchWorker.postMessage({type:"_init","in-port":b.port2},[b.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const b=this._jobWorkers.length;var c=this._runtimeInterface._GetWorkerURL("jobworker.js");c=await this._runtimeInterface.CreateWorker(c,this._baseUrl,{name:"JobWorker"+b});const e=new MessageChannel,h=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:e.port1},[e.port1]);c.postMessage({type:"init",number:b,"dispatch-port":e.port2,"output-port":h.port2},[e.port2,h.port2]);this._jobWorkers.push(c);return h.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!1,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptsType:"module",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"user-media");this.SetAutoAttach(!1);this._isRuntimeInWorker=this._iRuntime.UsesWorker();this._sequenceNumber=0;this._lastActiveStream=null;this.AddRuntimeMessageHandler("get-media-sources",()=>this._OnGetMediaSources());this.AddDOMElementMessageHandler("request-camera",(c,e)=>this._OnRequestCamera(c,e));this.AddDOMElementMessageHandler("request-microphone",(c,e)=>this._OnRequestMicrophone(c,e));this.AddDOMElementMessageHandler("snapshot",
(c,e)=>this._Snapshot(c,e));this.AddDOMElementMessageHandler("stop",c=>this._Stop(c));self.C3UserMedia_GetVideoElement=c=>this.GetElementById(c);self.C3UserMedia_GetLastMediaStream=()=>this._lastActiveStream}CreateElement(b,c){const e=document.createElement("video");e.crossOrigin="anonymous";e.autoplay=!0;e.muted=!0;e.playsInline=!0;e.addEventListener("canplaythrough",()=>{this.PostToRuntimeElement("video-ready",b,{width:e.videoWidth,height:e.videoHeight})});return e}UpdateState(b,c){}DestroyElement(b){b.srcObject&&
(this._StopStream(b.srcObject),b.srcObject=null)}_StopStream(b){this._lastActiveStream===b&&(this._lastActiveStream=null);b=b.getTracks();for(let c=0,e=b.length;c<e;++c)b[c].stop()}async _OnGetMediaSources(){const b=[],c=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var e=await navigator.mediaDevices.enumerateDevices();for(const h of e){e=h.kind;const l={deviceId:h.deviceId,label:h.label,facing:h.facing||h.facingMode||""};"video"===e||"videoinput"===e?b.push(l):("audio"===
e||"audioinput"===e)&&c.push(l)}}return{videoSources:b,audioSources:c}}async _OnRequestCamera(b,c){try{const e="object"===typeof c.constraints.audio,h=this.GetRuntimeInterface();e?await h.RequirePermissions("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await h.RequirePermissions("CAMERA");this._lastActiveStream=await navigator.mediaDevices.getUserMedia(c.constraints);b.srcObject=this._lastActiveStream;b.play();this._isRuntimeInWorker&&this._StartTicking();return{ok:!0}}catch(e){return console.warn("Error requesting camera: ",
e),{ok:!1}}}async _OnRequestMicrophone(b,c){try{return await this.GetRuntimeInterface().RequirePermissions("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),this._lastActiveStream=await navigator.mediaDevices.getUserMedia(c.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(this._lastActiveStream,c.tag),{ok:!0}}catch(e){return console.warn("Error requesting microphone: ",e),{ok:!1}}}_CanvasToURL(b,c,e){return new Promise((h,l)=>{b.toBlob?b.toBlob(p=>h(URL.createObjectURL(p)),c,e):
h(b.toDataURL(c,e))})}async _Snapshot(b,c){const e=document.createElement("canvas");e.width=b.videoWidth;e.height=b.videoHeight;e.getContext("2d").drawImage(b,0,0,b.videoWidth,b.videoHeight);return{snapshotUrl:await this._CanvasToURL(e,c.format,c.quality)}}_Stop(b){b.srcObject&&(this._StopStream(b.srcObject),b.srcObject=null)}Tick(){if(this._isRuntimeInWorker){var b={},c={sequenceNumber:this._sequenceNumber++,videoData:b},e=[],h=[];for(const [l,p]of this._elementMap.entries()){if(!p.srcObject)continue;
const n={};h.push(createImageBitmap(p).then(t=>{n.imageBitmap=t;e.push(t)}).catch(t=>{n.imageBitmap=null}));b[l.toString()]=n}Promise.all(h).then(()=>this.PostToRuntime("state",c,!1,e))}}});"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"button")}CreateElement(c,e){const h=document.createElement("input");var l=h;e.isCheckbox?(h.type="checkbox",l=document.createElement("label"),l.appendChild(h),l.appendChild(document.createTextNode("")),l.style.fontFamily="sans-serif",l.style.userSelect="none",l.style.webkitUserSelect="none",l.style.display="inline-block",l.style.color="black"):h.type="button";l.style.position=
"absolute";l.addEventListener("touchstart",b);l.addEventListener("touchmove",b);l.addEventListener("touchend",b);l.addEventListener("mousedown",b);l.addEventListener("mouseup",b);l.addEventListener("keydown",b);l.addEventListener("keyup",b);h.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",c,{isChecked:h.checked}));e.id&&(h.id=e.id);this.UpdateState(l,e);return l}_GetInputElem(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}_GetFocusElement(c){return this._GetInputElem(c)}UpdateState(c,
e){const h=this._GetInputElem(c);h.checked=e.isChecked;h.disabled=!e.isEnabled;c.title=e.title;c===h?h.value=e.text:c.lastChild.textContent=e.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",c=>this._OnGetInitialState(c)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",c=>this._OnAlert(c)],["close",()=>this._OnClose()],["set-focus",c=>this._OnSetFocus(c)],["vibrate",c=>this._OnVibrate(c)],["lock-orientation",c=>this._OnLockOrientation(c)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",c=>this._OnNavigate(c)],["request-fullscreen",c=>this._OnRequestFullscreen(c)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",c=>this._OnSetHash(c)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
c=>this._OnWin10BackRequested(c))}_OnGetInitialState(b){this._exportType=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(b=>
this.PostToRuntime("sw-message",b.data))}_OnOnlineStateChanged(b){this.PostToRuntime("online-state",{isOnline:b})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(b){b.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(b){alert(b.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(b){b=
b.isFocus;if("nwjs"===this._exportType){const c=this.GetNWjsWindow();b?c.focus():c.blur()}else b?window.focus():window.blur()}_OnVibrate(b){navigator.vibrate&&navigator.vibrate(b.pattern)}_OnLockOrientation(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):
screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(b){}}_OnNavigate(b){var c=b.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===c)window.forward();else if("home"===c)window.home();else if("reload"===c)location.reload();else if("url"===c){c=b.url;var e=b.target;b=b.exportType;"windows-uwp"===b&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(c,"_system"):"preview"===b?window.open(c,"_blank"):this._isScirraArcade||(2===e?window.top.location=c:1===e?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=b.url,e=b.tag,"windows-uwp"===b.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,e))}_OnRequestFullscreen(b){const c={navigationUI:"auto"};
b=b.navUI;1===b?c.navigationUI="hide":2===b&&(c.navigationUI="show");b=document.documentElement;b.requestFullscreen?b.requestFullscreen(c):b.mozRequestFullScreen?b.mozRequestFullScreen(c):b.msRequestFullscreen?b.msRequestFullscreen(c):b.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?b.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):b.webkitRequestFullScreen())}_OnExitFullscreen(){document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}_OnSetHash(b){location.hash=b.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"list");this.AddDOMElementMessageHandler("set-selected-index",(e,h)=>this._OnSetSelectedIndex(e,h.selectedIndex));this.AddDOMElementMessageHandler("add-item",(e,h)=>this._OnAddItem(e,h));this.AddDOMElementMessageHandler("remove-item",(e,h)=>this._OnRemoveItem(e,h));this.AddDOMElementMessageHandler("set-item",(e,h)=>this._OnSetItem(e,h));this.AddDOMElementMessageHandler("clear",
e=>this._OnClear(e));this.AddDOMElementMessageHandler("load-state",(e,h)=>this._OnLoadState(e,h))}CreateElement(c,e){const h=e.isDropdown,l=e.isMultiSelect,p=e.items,n=document.createElement("select");n.style.position="absolute";n.style.userSelect="none";n.style.webkitUserSelect="none";n.multiple=l;h||(n.size=2);for(const t of p)n.add(this._CreateOption(t));n.addEventListener("touchstart",b);n.addEventListener("touchmove",b);n.addEventListener("touchend",b);n.addEventListener("mousedown",b);n.addEventListener("mouseup",
b);n.addEventListener("click",t=>{t.stopPropagation();this._PostToRuntimeElementMaybeSync("click",c,this._GetSelectionState(n))});n.addEventListener("dblclick",t=>{t.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",c,this._GetSelectionState(n))});n.addEventListener("change",()=>this.PostToRuntimeElement("change",c,this._GetSelectionState(n)));e.id&&(n.id=e.id);this.UpdateState(n,e);return n}_CreateOption(c){const e=document.createElement("option");e.text=c;return e}_GetSelectionState(c){const e=
c.selectedIndex,h=[];for(let l=0,p=c.length;l<p;++l)c.options[l].selected&&h.push(l);return{selectedIndex:e,selectedIndices:h}}UpdateState(c,e){c.title=e.title;c.disabled=!e.isEnabled;c.multiple=!!e.isMultiSelect}_OnSetSelectedIndex(c,e){c.selectedIndex=e}_OnAddItem(c,e){const h=e.index;e=this._CreateOption(e.text);0>h?c.add(e):c.add(e,h)}_OnRemoveItem(c,e){c.remove(e.index)}_OnSetItem(c,e){c.options[e.index].text=e.text}_OnClear(c){c.innerHTML=""}_OnLoadState(c,e){c.innerHTML="";for(const h of e.items)c.add(this._CreateOption(h));
c.selectedIndex=e.selectedIndex;for(const h of e.selectedIndices)if(e=c.options[h])e.selected=!0}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"game-recorder");this._mediaStream=this._mediaRecorder=null;this._stopStreamOnEnd=!0;this._recordedChunks=[];this._lastRecordingUrl="";this.AddRuntimeMessageHandler("get-supported-formats",()=>this._OnGetSupportedFormats());this.AddRuntimeMessageHandler("start-recording",c=>this._OnStartRecording(c));this.AddRuntimeMessageHandler("start-screen-recording",c=>this._OnStartScreenRecording(c));this.AddRuntimeMessageHandler("start-user-media-recording",
c=>this._OnStartUserMediaRecording(c));this.AddRuntimeMessageHandler("stop-recording",()=>this._OnStopRecording());this._MaybePolyfillGetDisplayMedia()}_MaybePolyfillGetDisplayMedia(){navigator.mediaDevices&&navigator.mediaDevices.getDisplayMedia||navigator.mediaDevices&&navigator.mediaDevices.getSupportedConstraints&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getSupportedConstraints().mediaSource&&(navigator.mediaDevices.getDisplayMedia=function(){return navigator.mediaDevices.getUserMedia({video:{mediaSource:"screen"}})})}_OnGetSupportedFormats(){var b=
this._iRuntime.GetCanvas();const c="undefined"!==typeof MediaRecorder;b=!(!b.captureStream||!c);const e=[],h=[];b&&(MediaRecorder.isTypeSupported("video/mp4")&&e.push("video/mp4"),MediaRecorder.isTypeSupported("video/webm;codecs=vp8")&&e.push("video/webm;codecs=vp8"),MediaRecorder.isTypeSupported("video/webm;codecs=vp9")&&e.push("video/webm;codecs=vp9"),MediaRecorder.isTypeSupported("audio/mp4")&&h.push("audio/mp4"),MediaRecorder.isTypeSupported("audio/ogg;codecs=opus")&&h.push("audio/ogg;codecs=opus"),
MediaRecorder.isTypeSupported("audio/webm;codecs=opus")&&h.push("audio/webm;codecs=opus"));return{isSupported:b,isMediaRecorderSupported:c,isScreenRecordingSupported:!(!navigator.mediaDevices||!navigator.mediaDevices.getDisplayMedia||"undefined"===typeof MediaRecorder),supportedVideoFormats:e,supportedAudioFormats:h}}_StopStreamVideoTracks(b){b=b.getTracks();for(let c=0,e=b.length;c<e;++c){const h=b[c];"video"===h.kind&&h.stop()}}_StopAnyPriorRecording(){this._OnStopRecording();this._recordedChunks.length=
0;this._lastRecordingUrl&&(URL.revokeObjectURL(this._lastRecordingUrl),this._lastRecordingUrl="")}_OnStartRecording(b){const c=b.videoType,e=b.audioType,h=b.bitsPerSecond;b=b.framerate;this._StopAnyPriorRecording();let l=[],p=[];try{if(c){const n=this._iRuntime.GetCanvas();l=(0<b?n.captureStream(b):n.captureStream()).getVideoTracks()}e&&self.C3Audio_GetOutputStream&&(p=self.C3Audio_GetOutputStream().getAudioTracks());this._mediaStream=new MediaStream([...l,...p]);this._stopStreamOnEnd=!0;this._mediaRecorder=
new MediaRecorder(this._mediaStream,{mimeType:c||e,bitsPerSecond:h})}catch(n){console.error("[Game Recorder] Failed to start recording: ",n),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}async _OnStartScreenRecording(b){const c=b.videoType,e=b.audioType;b=b.bitsPerSecond;this._StopAnyPriorRecording();let h=[],l=[];try{c&&(h=(await navigator.mediaDevices.getDisplayMedia({video:!0})).getVideoTracks()),e&&self.C3Audio_GetOutputStream&&(l=self.C3Audio_GetOutputStream().getAudioTracks()),this._mediaStream=
new MediaStream([...h,...l]),this._stopStreamOnEnd=!0,this._mediaStream.addEventListener("inactive",()=>this._OnMediaStreamInactive()),this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:c||e,bitsPerSecond:b})}catch(p){console.error("[Game Recorder] Failed to start recording: ",p),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}async _OnStartUserMediaRecording(b){const c=b.videoType,e=b.audioType;b=b.bitsPerSecond;this._StopAnyPriorRecording();if(self.C3UserMedia_GetLastMediaStream){var h=
self.C3UserMedia_GetLastMediaStream();if(h){try{this._mediaStream=h,this._stopStreamOnEnd=!1,this._mediaRecorder=new MediaRecorder(this._mediaStream,{mimeType:c||e,bitsPerSecond:b})}catch(l){console.error("[Game Recorder] Failed to start recording: ",l),this.PostToRuntime("error")}this._StartMediaRecorder(c,e)}}}_StartMediaRecorder(b,c){this._mediaRecorder.ondataavailable=e=>{this._recordedChunks.push(e.data)};this._mediaRecorder.onerror=e=>{console.error("[Game Recorder] Error recording: ",e);this.PostToRuntime("error")};
this._mediaRecorder.onwarning=e=>{console.warn("[Game Recorder] Recording warning: ",e)};this._mediaRecorder.onstop=e=>{e=new Blob(this._recordedChunks,{type:b||c});this._lastRecordingUrl=URL.createObjectURL(e);this.PostToRuntime("recording-ready",{url:this._lastRecordingUrl})};this._mediaRecorder.start()}_OnMediaStreamInactive(){this.PostToRuntime("screen-recording-stopped");this._OnStopRecording()}_OnStopRecording(){this._mediaRecorder&&(this._mediaRecorder.stop(),this._mediaRecorder=null);this._mediaStream&&
(this._stopStreamOnEnd&&this._StopStreamVideoTracks(this._mediaStream),this._mediaStream=null)}});"use strict";
{function b(e){e.stopPropagation()}function c(e){13!==e.which&&27!==e.which&&e.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(e){super(e,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",h=>this._OnScrollToBottom(h))}CreateElement(e,h){let l;const p=h.type;"textarea"===p?(l=document.createElement("textarea"),l.style.resize="none"):(l=document.createElement("input"),l.type=p);l.style.position="absolute";l.autocomplete="off";
l.addEventListener("touchstart",b);l.addEventListener("touchmove",b);l.addEventListener("touchend",b);l.addEventListener("mousedown",b);l.addEventListener("mouseup",b);l.addEventListener("keydown",c);l.addEventListener("keyup",c);l.addEventListener("click",n=>{n.stopPropagation();this._PostToRuntimeElementMaybeSync("click",e)});l.addEventListener("dblclick",n=>{n.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",e)});l.addEventListener("input",()=>this.PostToRuntimeElement("change",
e,{text:l.value}));h.id&&(l.id=h.id);this.UpdateState(l,h);return l}UpdateState(e,h){e.value=h.text;e.placeholder=h.placeholder;e.title=h.title;e.disabled=!h.isEnabled;e.readOnly=h.isReadOnly;e.spellcheck=h.spellCheck;h=h.maxLength;0>h?e.removeAttribute("maxlength"):e.setAttribute("maxlength",h)}_OnScrollToBottom(e){e.scrollTop=e.scrollHeight}})}"use strict";
{function b(c){c.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(c){super(c,"sliderbar")}CreateElement(c,e){const h=document.createElement("input");h.type="range";h.style.position="absolute";h.style.userSelect="none";h.style.webkitUserSelect="none";h.addEventListener("touchstart",b);h.addEventListener("touchmove",b);h.addEventListener("touchend",b);h.addEventListener("mousedown",b);h.addEventListener("mouseup",b);h.addEventListener("keydown",
b);h.addEventListener("keyup",b);h.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",c));h.addEventListener("change",()=>this.PostToRuntimeElement("change",c,{value:parseFloat(h.value)}));h.addEventListener("input",()=>this.PostToRuntimeElement("input",c,{value:parseFloat(h.value)}));e.id&&(h.id=e.id);this.UpdateState(h,e);return h}UpdateState(c,e){c.max=e.max;c.min=e.min;c.step=e.step;c.value=e.value;c.disabled=!e.isEnabled;c.title=e.title}})};
