{
	"version": 1644666683,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/title-sheet0.png",
		"images/box-sheet0.png",
		"images/box2-sheet0.png",
		"images/box3-sheet0.png",
		"images/ball-sheet0.png",
		"images/deska-sheet0.png",
		"images/wall-sheet0.png",
		"images/pudlo-sheet0.png",
		"images/carousel-sheet0.png",
		"images/star-sheet0.png",
		"images/arrow-sheet0.png",
		"images/carousel2-sheet0.png",
		"images/wall2-sheet0.png",
		"images/pudlo2-sheet0.png",
		"images/particles.png",
		"images/spritefont.png",
		"images/pdnp-sheet0.png",
		"images/star2-sheet0.png",
		"images/wall3rotate-sheet0.png",
		"images/button-sheet0.png",
		"images/button2-sheet0.png",
		"images/door-sheet0.png",
		"images/particles2.png",
		"images/fan-sheet0.png",
		"images/trap-sheet0.png",
		"images/wind-sheet0.png",
		"images/particles3.png",
		"images/sprite-sheet0.png",
		"images/enn-sheet0.png",
		"images/aaaa-sheet0.png",
		"images/aaaa-sheet1.png",
		"images/cb-sheet0.png",
		"images/ball3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/rubber-sheet0.png",
		"media/randomizea.m4a",
		"media/randomizea.ogg",
		"media/select2.m4a",
		"media/select2.ogg",
		"media/begin.m4a",
		"media/begin.ogg",
		"media/destroy.m4a",
		"media/destroy.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/trap.m4a",
		"media/trap.ogg",
		"media/pickup.m4a",
		"media/pickup.ogg",
		"media/8bit music 1.m4a",
		"media/8bit music 1.ogg",
		"media/8bit music 3.m4a",
		"media/8bit music 3.ogg",
		"media/8bit music 2.m4a",
		"media/8bit music 2.ogg",
		"media/8bit music 4.m4a",
		"media/8bit music 4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}