{
	"version": 1609237532,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/1player-sheet0.png",
		"images/1player-sheet1.png",
		"images/1player-sheet2.png",
		"images/cel-sheet0.png",
		"images/camera-sheet0.png",
		"images/entites-sheet0.png",
		"images/wind-sheet0.png",
		"images/wind2-sheet0.png",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"images/background-sheet2.png",
		"images/duzepeknieciesheet-sheet0.png",
		"images/slot-sheet0.png",
		"images/slot-sheet1.png",
		"images/slot-sheet2.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/stats.png",
		"images/stats2.png",
		"images/spritefont.png",
		"images/cooltext-sheet0.png",
		"images/radioactivesymbol1600x-sheet0.png",
		"images/reka-sheet0.png",
		"images/reka-sheet1.png",
		"images/grabarea-sheet0.png",
		"images/pockettext-sheet0.png",
		"images/‏wlosy-sheet0.png",
		"images/‏wlosy-sheet1.png",
		"images/cooltextskill-sheet0.png",
		"images/cooltextinv-sheet0.png",
		"images/cooltextstats-sheet0.png",
		"images/asfalt-sheet0.png",
		"images/asfalt-sheet1.png",
		"images/hpbar-sheet0.png",
		"images/thirstbar-sheet0.png",
		"images/hungerbar-sheet0.png",
		"images/lvupmessage.png",
		"images/oko-sheet0.png",
		"images/oko-sheet1.png",
		"images/oko-sheet2.png",
		"images/hungerbar2-sheet0.png",
		"images/polskanke-sheet0.png",
		"images/lornetka-sheet0.png",
		"images/rozmowa-sheet0.png",
		"images/rozmowa-sheet1.png",
		"images/rozmowa-sheet2.png",
		"images/source-sheet0.png",
		"images/source-sheet1.png",
		"images/mesages.png",
		"images/slotweapon-sheet0.png",
		"images/slotweapon-sheet1.png",
		"images/zrzutekranu-sheet0.png",
		"images/sanddunes-sheet0.png",
		"images/cam-sheet0.png",
		"images/sprite-sheet0.png",
		"images/flash-sheet0.png",
		"images/wilk-sheet0.png",
		"images/wilk-sheet1.png",
		"images/jaszcz2aligator-sheet0.png",
		"images/jaszcz2aligator-sheet1.png",
		"images/1lura-sheet0.png",
		"images/1lura-sheet1.png",
		"images/stats4.png",
		"images/waran-sheet0.png",
		"images/chupacabra-sheet0.png",
		"images/chupacabra-sheet1.png",
		"images/grabarea2-sheet0.png",
		"images/kot-sheet0.png",
		"images/kot-sheet1.png",
		"images/kamien-sheet0.png",
		"images/dom-sheet0.png",
		"images/dom-sheet1.png",
		"images/trees-sheet0.png",
		"images/trees-sheet1.png",
		"images/zegar-sheet0.png",
		"images/zegar-sheet1.png",
		"images/zzz-sheet0.png",
		"images/zzz-sheet1.png",
		"images/piq51948400x-sheet0.png",
		"images/sword-sheet0.png",
		"images/slotarmor-sheet0.png",
		"images/pora-sheet0.png",
		"images/pora-sheet1.png",
		"images/cel2-sheet0.png",
		"images/blood-sheet0.png",
		"images/hitanimation-sheet0.png",
		"images/map-sheet0.png",
		"images/kot2-sheet0.png",
		"images/thebonesinthedesert-sheet0.png",
		"images/ufo-sheet0.png",
		"images/ufo2-sheet0.png",
		"images/ufo3ray-sheet0.png",
		"images/cooltext4-sheet0.png",
		"images/tiledbackground7.png",
		"images/outside_a-sheet0.png",
		"images/whell-sheet0.png",
		"images/whell-sheet1.png",
		"images/nora-sheet0.png",
		"images/ant-sheet0.png",
		"images/ant-sheet1.png",
		"images/slotpistol-sheet0.png",
		"images/slotpistol-sheet1.png",
		"images/slotpistol-sheet2.png",
		"images/bullethit-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/domtop-sheet0.png",
		"images/robot-sheet0.png",
		"images/robot-sheet1.png",
		"images/robot2-sheet0.png",
		"images/domwew-sheet0.png",
		"images/kot3-sheet0.png",
		"images/kot3-sheet1.png",
		"images/slotweapon2-sheet0.png",
		"images/player2-sheet0.png",
		"images/player2-sheet1.png",
		"images/alienmech-sheet0.png",
		"images/alienmech-sheet1.png",
		"images/laser-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground8.png",
		"images/tiledbackground9.png",
		"images/wybuchpiaslkowy-sheet0.png",
		"images/wybuchpiaslkowy-sheet1.png",
		"images/soldier-sheet0.png",
		"images/soldier-sheet1.png",
		"images/bloodspill-sheet0.png",
		"images/bloodspill-sheet1.png",
		"images/a_tent_by_valforwing-sheet0.png",
		"images/hungerbar3-sheet0.png",
		"images/tempbar-sheet0.png",
		"images/arrow-sheet0.png",
		"images/luradodomu-sheet0.png",
		"images/tiledbackground10.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/spritefont3.png",
		"images/spritefont4.png",
		"images/spritrfontskill.png",
		"images/asfalt2-sheet0.png",
		"images/lightexplosion-sheet0.png",
		"images/fireplace-sheet0.png",
		"images/fireplace-sheet1.png",
		"images/plus-sheet0.png",
		"images/plus-sheet1.png",
		"images/abandoned-sheet0.png",
		"images/adeptus2-sheet0.png",
		"images/12hpperlevel-sheet0.png",
		"images/highquantityof-sheet0.png",
		"images/highquantityof-sheet1.png",
		"images/combine-sheet0.png",
		"images/combine-sheet1.png",
		"images/combine-sheet2.png",
		"images/marker-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/slothead-sheet0.png",
		"images/slothead-sheet1.png",
		"images/play-sheet0.png",
		"images/napoludnie-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/napolnoc-sheet0.png",
		"images/gwozdzie_podkowiaki-sheet0.png",
		"images/bootstomp-sheet0.png",
		"images/slotboots-sheet0.png",
		"images/barsoldier-sheet0.png",
		"images/xptext-sheet0.png",
		"images/xptext-sheet1.png",
		"images/xptext-sheet2.png",
		"images/chest-sheet0.png",
		"images/chest-sheet1.png",
		"images/lightfireplace2-sheet0.png",
		"images/chest2-sheet0.png",
		"images/chest2-sheet1.png",
		"images/npcghost-sheet0.png",
		"images/fence-sheet0.png",
		"images/fence-sheet1.png",
		"images/fence-sheet2.png",
		"images/tiledfence.png",
		"images/tiledfence2.png",
		"images/fence2.png",
		"images/fence3.png",
		"images/corpse-sheet0.png",
		"images/corpse-sheet1.png",
		"images/explosionbarrel-sheet0.png",
		"images/explosionbarell-sheet0.png",
		"images/explosionbarell-sheet1.png",
		"images/bulletpl-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/sprite10-sheet2.png",
		"images/tiledbackground11.png",
		"images/tilemap2.png",
		"images/lurahpbar-sheet0.png",
		"images/luraleveltxt-sheet0.png",
		"images/lurahpbar2-sheet0.png",
		"images/lurahpbar3-sheet0.png",
		"images/minus-sheet0.png",
		"images/minus-sheet1.png",
		"images/sprite11-sheet0.png",
		"images/desert-sheet0.png",
		"images/jag-sheet0.png",
		"images/jag2-sheet0.png",
		"images/dialogboard-sheet0.png",
		"images/dialog.png",
		"images/npc1-sheet0.png",
		"images/dialogfield-sheet0.png",
		"images/npc2-sheet0.png",
		"images/pipes-sheet0.png",
		"images/pipes-sheet1.png",
		"images/pipes-sheet2.png",
		"images/inside_a_well_by_toonimated-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/npc3-sheet0.png",
		"images/npc3-sheet1.png",
		"images/tiledbackground12.png",
		"images/steel_dawn_by_dekokatanad5m39ee-sheet0.png",
		"images/sprite13-sheet0.png",
		"media/dirt_sand_03_001.m4a",
		"media/dirt_sand_03_001.ogg",
		"media/grab.m4a",
		"media/grab.ogg",
		"media/search.m4a",
		"media/search.ogg",
		"media/trigger_click_001.m4a",
		"media/trigger_click_001.ogg",
		"media/lvup.m4a",
		"media/lvup.ogg",
		"media/geiger counter sound (256kbit).m4a",
		"media/geiger counter sound (256kbit).ogg",
		"media/drinking water.m4a",
		"media/drinking water.ogg",
		"media/nalewanie wody.m4a",
		"media/nalewanie wody.ogg",
		"media/odetkanie butelki.m4a",
		"media/odetkanie butelki.ogg",
		"media/eat.m4a",
		"media/eat.ogg",
		"media/equip1wep.m4a",
		"media/equip1wep.ogg",
		"media/equip2cloth.m4a",
		"media/equip2cloth.ogg",
		"media/monstereat.m4a",
		"media/monstereat.ogg",
		"media/jaguar attack.m4a",
		"media/jaguar attack.ogg",
		"media/jaguar eat_001.m4a",
		"media/jaguar eat_001.ogg",
		"media/step1.m4a",
		"media/step1.ogg",
		"media/flash point hit_04.m4a",
		"media/flash point hit_04.ogg",
		"media/knife_hit3.m4a",
		"media/knife_hit3.ogg",
		"media/uforay.m4a",
		"media/uforay.ogg",
		"media/a_wolf1.m4a",
		"media/a_wolf1.ogg",
		"media/scrm.m4a",
		"media/scrm.ogg",
		"media/wolf growl 12.m4a",
		"media/wolf growl 12.ogg",
		"media/pistol_fire2.m4a",
		"media/pistol_fire2.ogg",
		"media/fx_laser_impact_04.m4a",
		"media/fx_laser_impact_04.ogg",
		"media/laser1.m4a",
		"media/laser1.ogg",
		"media/laser gun.m4a",
		"media/laser gun.ogg",
		"media/fx_explosion_robot_bzzzt_01.m4a",
		"media/fx_explosion_robot_bzzzt_01.ogg",
		"media/drop armor.m4a",
		"media/drop armor.ogg",
		"media/drop pistol.m4a",
		"media/drop pistol.ogg",
		"media/a metal weapon is dropped.m4a",
		"media/a metal weapon is dropped.ogg",
		"media/fx_laser_impact_03.m4a",
		"media/fx_laser_impact_03.ogg",
		"media/blow6.m4a",
		"media/blow6.ogg",
		"media/fx_laser_impact_02.m4a",
		"media/fx_laser_impact_02.ogg",
		"media/bow.m4a",
		"media/bow.ogg",
		"media/big fire (2).m4a",
		"media/big fire (2).ogg",
		"media/laser organic.m4a",
		"media/laser organic.ogg",
		"media/score.m4a",
		"media/score.ogg",
		"media/188606__timpryor__woodcreak.m4a",
		"media/188606__timpryor__woodcreak.ogg",
		"media/metal hit 01 sound effects (256kbit).m4a",
		"media/metal hit 01 sound effects (256kbit).ogg",
		"media/metal hit 02 sound effects (256kbit).m4a",
		"media/metal hit 02 sound effects (256kbit).ogg",
		"media/metal hit 03 sound effects (256kbit).m4a",
		"media/metal hit 03 sound effects (256kbit).ogg",
		"media/metal hit 04 sound effects (256kbit).m4a",
		"media/metal hit 04 sound effects (256kbit).ogg",
		"media/metal hit 05 sound effects (256kbit).m4a",
		"media/metal hit 05 sound effects (256kbit).ogg",
		"media/metal hit 06 sound effects (256kbit).m4a",
		"media/metal hit 06 sound effects (256kbit).ogg",
		"media/metal hit 08 sound effects (256kbit).m4a",
		"media/metal hit 08 sound effects (256kbit).ogg",
		"media/metal hit 09 sound effects (256kbit).m4a",
		"media/metal hit 09 sound effects (256kbit).ogg",
		"media/wall hit 01 sound effects (256kbit).m4a",
		"media/wall hit 01 sound effects (256kbit).ogg",
		"media/wall hit 04 sound effects (256kbit).m4a",
		"media/wall hit 04 sound effects (256kbit).ogg",
		"media/fire_vehicle_flame_up_medbig2.m4a",
		"media/fire_vehicle_flame_up_medbig2.ogg",
		"media/dirt_sand_01.m4a",
		"media/dirt_sand_01.ogg",
		"media/dirt_sand_07.m4a",
		"media/dirt_sand_07.ogg",
		"media/ricochet_01.m4a",
		"media/ricochet_01.ogg",
		"media/ricochet_02.m4a",
		"media/ricochet_02.ogg",
		"media/ricochet_03.m4a",
		"media/ricochet_03.ogg",
		"media/ricochet_04.m4a",
		"media/ricochet_04.ogg",
		"media/ricochet_05.m4a",
		"media/ricochet_05.ogg",
		"media/ricochet_06.m4a",
		"media/ricochet_06.ogg",
		"media/ricochet_07.m4a",
		"media/ricochet_07.ogg",
		"media/ricochet_08.m4a",
		"media/ricochet_08.ogg",
		"media/ricochet_09.m4a",
		"media/ricochet_09.ogg",
		"media/ricochet_10.m4a",
		"media/ricochet_10.ogg",
		"media/ricochet_11.m4a",
		"media/ricochet_11.ogg",
		"media/ricochet_12.m4a",
		"media/ricochet_12.ogg",
		"media/ricochet_13.m4a",
		"media/ricochet_13.ogg",
		"media/ricochet_14.m4a",
		"media/ricochet_14.ogg",
		"media/ricochet_15.m4a",
		"media/ricochet_15.ogg",
		"media/ricochet_metal_01.m4a",
		"media/ricochet_metal_01.ogg",
		"media/ricochet_metal_02.m4a",
		"media/ricochet_metal_02.ogg",
		"media/ricochet_metal_03.m4a",
		"media/ricochet_metal_03.ogg",
		"media/ricochet_metal_04.m4a",
		"media/ricochet_metal_04.ogg",
		"media/ricochet_metal_05.m4a",
		"media/ricochet_metal_05.ogg",
		"media/ricochet_metal_06.m4a",
		"media/ricochet_metal_06.ogg",
		"media/ricochet_metal_07.m4a",
		"media/ricochet_metal_07.ogg",
		"media/ricochet_metal_08.m4a",
		"media/ricochet_metal_08.ogg",
		"media/ricochet_metal_09.m4a",
		"media/ricochet_metal_09.ogg",
		"media/wood_01.m4a",
		"media/wood_01.ogg",
		"media/wood_02.m4a",
		"media/wood_02.ogg",
		"media/wood_03.m4a",
		"media/wood_03.ogg",
		"media/wood_04.m4a",
		"media/wood_04.ogg",
		"media/wood_05.m4a",
		"media/wood_05.ogg",
		"media/wood_06.m4a",
		"media/wood_06.ogg",
		"media/ak47_reload.m4a",
		"media/ak47_reload.ogg",
		"media/bandadge.m4a",
		"media/bandadge.ogg",
		"media/ant_001.m4a",
		"media/ant_001.ogg",
		"media/ant dead.m4a",
		"media/ant dead.ogg",
		"media/typewriter.m4a",
		"media/typewriter.ogg",
		"media/typewriter2.m4a",
		"media/typewriter2.ogg",
		"media/futurisitc ui sound 19.m4a",
		"media/futurisitc ui sound 19.ogg",
		"media/tigerattack.m4a",
		"media/tigerattack.ogg",
		"media/wnd ambience dark2.m4a",
		"media/wnd ambience dark2.ogg",
		"media/wnd ambience dark3.m4a",
		"media/wnd ambience dark3.ogg",
		"media/cannonfaraway.m4a",
		"media/cannonfaraway.ogg",
		"media/artillery distance.m4a",
		"media/artillery distance.ogg",
		"media/the sound of the moon .m4a",
		"media/the sound of the moon .ogg",
		"media/snore.m4a",
		"media/snore.ogg",
		"media/planet villige_001.m4a",
		"media/planet villige_001.ogg",
		"media/nasa space 4_001.m4a",
		"media/nasa space 4_001.ogg",
		"media/planet droid.m4a",
		"media/planet droid.ogg",
		"media/nasa space 7_001.m4a",
		"media/nasa space 7_001.ogg",
		"media/laser loop.m4a",
		"media/laser loop.ogg",
		"media/222.m4a",
		"media/222.ogg",
		"media/222_001.m4a",
		"media/222_001.ogg",
		"media/desertroamer.m4a",
		"media/desertroamer.ogg",
		"media/action.m4a",
		"media/action.ogg",
		"media/city darkness.m4a",
		"media/city darkness.ogg",
		"media/city villige.m4a",
		"media/city villige.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"jquery.gritter.js",
		"jquery.gritter.css",
		"pathfind.js"
	]
}